// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Services.Libraries.Database;

#nullable disable

namespace Services.Libraries.Database.Migrations
{
    [DbContext(typeof(LibrariesContext))]
    [Migration("20260519170633_Add-Service-Mappings")]
    partial class AddServiceMappings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Services.Libraries.Database.DbLibrary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LibraryType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("Services.Libraries.Database.DbServiceDirectoryMapping", b =>
                {
                    b.Property<Guid>("MappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServicePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrangaPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MappingId");

                    b.HasIndex("LibraryId");

                    b.ToTable("DirectoryMappings");
                });

            modelBuilder.Entity("Services.Libraries.Database.DbServiceDirectoryMapping", b =>
                {
                    b.HasOne("Services.Libraries.Database.DbLibrary", "Library")
                        .WithMany("ServiceDirectoryMappings")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Services.Libraries.Database.DbLibrary", b =>
                {
                    b.Navigation("ServiceDirectoryMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
