# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/runtime:7.0 as runtime
WORKDIR /publish

# Install necessary dependencies in a single RUN command to reduce image size and improve build time
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libx11-6 \
        libx11-xcb1 \
        libatk1.0-0 \
        libgtk-3-0 \
        libcups2 \
        libdrm2 \
        libxkbcommon0 \
        libxcomposite1 \
        libxdamage1 \
        libxrandr2 \
        libgbm1 \
        libpango-1.0-0 \
        libcairo2 \
        libasound2 \
        libxshmfence1 \
        libnss3 \
        curl && \
    apt-get autopurge -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
