// <auto-generated />
using System;
using Database.MangaContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Database.MangaContext.Migrations
{
    [DbContext(typeof(MangaContext))]
    [Migration("20260407180637_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Database.MangaContext.DbChapter", b =>
                {
                    b.Property<Guid>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MangaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Volume")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("ChapterId");

                    b.HasIndex("MangaId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Database.MangaContext.DbChapterDownloadLink", b =>
                {
                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DownloadExtension")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("ChapterId", "DownloadExtension");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("ChapterDownloadLinks");
                });

            modelBuilder.Entity("Database.MangaContext.DbDownloadLink", b =>
                {
                    b.Property<Guid>("DownloadLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DownloadExtension")
                        .HasColumnType("uuid");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool?>("NSFW")
                        .HasColumnType("boolean");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Summary")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("DownloadLinkId");

                    b.HasIndex("CoverId")
                        .IsUnique();

                    b.ToTable("DownloadLinks");
                });

            modelBuilder.Entity("Database.MangaContext.DbFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FileId");

                    b.HasIndex(new[] { "Path", "Name" }, "IX_File_Path_Name");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Database.MangaContext.DbGenre", b =>
                {
                    b.Property<string>("Genre")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Genre");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Database.MangaContext.DbManga", b =>
                {
                    b.Property<Guid>("MangaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Monitored")
                        .HasColumnType("boolean");

                    b.HasKey("MangaId");

                    b.ToTable("Mangas");
                });

            modelBuilder.Entity("Database.MangaContext.DbMangaArtists", b =>
                {
                    b.Property<string>("ArtistId")
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("MetadataId")
                        .HasColumnType("uuid");

                    b.HasKey("ArtistId", "MetadataId");

                    b.HasIndex("MetadataId");

                    b.ToTable("DbMangaArtists");
                });

            modelBuilder.Entity("Database.MangaContext.DbMangaAuthors", b =>
                {
                    b.Property<string>("AuthorId")
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("MetadataId")
                        .HasColumnType("uuid");

                    b.HasKey("AuthorId", "MetadataId");

                    b.HasIndex("MetadataId");

                    b.ToTable("DbMangaAuthors");
                });

            modelBuilder.Entity("Database.MangaContext.DbMangaDownloadLinks", b =>
                {
                    b.Property<Guid>("MangaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DownloadLinkId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Matched")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("MangaId", "DownloadLinkId");

                    b.HasIndex("DownloadLinkId");

                    b.ToTable("MangaDownloadLinks");
                });

            modelBuilder.Entity("Database.MangaContext.DbMangaGenres", b =>
                {
                    b.Property<Guid>("MetadataId")
                        .HasColumnType("uuid");

                    b.Property<string>("GenreId")
                        .HasColumnType("character varying(128)");

                    b.HasKey("MetadataId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("DbMangaGenres");
                });

            modelBuilder.Entity("Database.MangaContext.DbMangaMetadataEntries", b =>
                {
                    b.Property<Guid>("MangaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MetadataId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Chosen")
                        .HasColumnType("boolean");

                    b.HasKey("MangaId", "MetadataId");

                    b.HasIndex("MetadataId");

                    b.ToTable("MangaMetadataEntries");
                });

            modelBuilder.Entity("Database.MangaContext.DbMetadata", b =>
                {
                    b.Property<Guid>("MetadataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ChaptersNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CoverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("MetadataExtension")
                        .HasColumnType("uuid");

                    b.Property<bool?>("NSFW")
                        .HasColumnType("boolean");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("MetadataId");

                    b.HasIndex("CoverId")
                        .IsUnique();

                    b.HasIndex(new[] { "MetadataExtension", "Identifier" }, "IX_Metadata_Extension_Identifier");

                    b.ToTable("MetadataEntries");
                });

            modelBuilder.Entity("Database.MangaContext.DbPerson", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Name");

                    b.ToTable("DbPerson");
                });

            modelBuilder.Entity("Database.MangaContext.DbChapter", b =>
                {
                    b.HasOne("Database.MangaContext.DbManga", "Manga")
                        .WithMany("Chapters")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("Database.MangaContext.DbChapterDownloadLink", b =>
                {
                    b.HasOne("Database.MangaContext.DbChapter", "Chapter")
                        .WithMany("DownloadLinks")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.MangaContext.DbFile", "File")
                        .WithOne()
                        .HasForeignKey("Database.MangaContext.DbChapterDownloadLink", "FileId");

                    b.Navigation("Chapter");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Database.MangaContext.DbDownloadLink", b =>
                {
                    b.HasOne("Database.MangaContext.DbFile", "Cover")
                        .WithOne()
                        .HasForeignKey("Database.MangaContext.DbDownloadLink", "CoverId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cover");
                });

            modelBuilder.Entity("Database.MangaContext.DbMangaArtists", b =>
                {
                    b.HasOne("Database.MangaContext.DbPerson", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.MangaContext.DbMetadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Database.MangaContext.DbMangaAuthors", b =>
                {
                    b.HasOne("Database.MangaContext.DbPerson", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.MangaContext.DbMetadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Database.MangaContext.DbMangaDownloadLinks", b =>
                {
                    b.HasOne("Database.MangaContext.DbDownloadLink", "DownloadLink")
                        .WithMany("MangaMatches")
                        .HasForeignKey("DownloadLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.MangaContext.DbManga", "Manga")
                        .WithMany("DownloadLinks")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DownloadLink");

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("Database.MangaContext.DbMangaGenres", b =>
                {
                    b.HasOne("Database.MangaContext.DbGenre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.MangaContext.DbMetadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Database.MangaContext.DbMangaMetadataEntries", b =>
                {
                    b.HasOne("Database.MangaContext.DbManga", "Manga")
                        .WithMany("MetadataEntries")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.MangaContext.DbMetadata", "Metadata")
                        .WithMany("MangaMetadataEntries")
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manga");

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Database.MangaContext.DbMetadata", b =>
                {
                    b.HasOne("Database.MangaContext.DbFile", "Cover")
                        .WithOne()
                        .HasForeignKey("Database.MangaContext.DbMetadata", "CoverId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cover");
                });

            modelBuilder.Entity("Database.MangaContext.DbChapter", b =>
                {
                    b.Navigation("DownloadLinks");
                });

            modelBuilder.Entity("Database.MangaContext.DbDownloadLink", b =>
                {
                    b.Navigation("MangaMatches");
                });

            modelBuilder.Entity("Database.MangaContext.DbManga", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("DownloadLinks");

                    b.Navigation("MetadataEntries");
                });

            modelBuilder.Entity("Database.MangaContext.DbMetadata", b =>
                {
                    b.Navigation("MangaMetadataEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
