// <auto-generated />
using System;
using Database.MangaContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Database.MangaContext.Migrations
{
    [DbContext(typeof(MangaContext))]
    partial class MangaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Database.MangaContext.DbChapter", b =>
                {
                    b.Property<Guid>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Chapter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("MangaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Volume")
                        .HasColumnType("text");

                    b.HasKey("ChapterId");

                    b.HasIndex("MangaId");

                    b.ToTable("Chapter", (string)null);
                });

            modelBuilder.Entity("Database.MangaContext.DbManga", b =>
                {
                    b.Property<Guid>("MangaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AgeRating")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Artists")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Authors")
                        .HasColumnType("text[]");

                    b.Property<string>("CoverImageBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Genre")
                        .HasColumnType("text[]");

                    b.Property<long?>("MangaUpdatesSeriesId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string[]>("Tags")
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("MangaId");

                    b.ToTable("Manga", (string)null);
                });

            modelBuilder.Entity("Database.MangaContext.DownloadExtensionId<Database.MangaContext.DbChapter>", b =>
                {
                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<Guid>("ExtensionIdentifier")
                        .HasColumnType("uuid");

                    b.HasKey("ParentId", "Identifier");

                    b.ToTable("ChapterDownloadExtensionIds", (string)null);
                });

            modelBuilder.Entity("Database.MangaContext.DownloadExtensionId<Database.MangaContext.DbManga>", b =>
                {
                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<Guid?>("DbMangaMangaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExtensionIdentifier")
                        .HasColumnType("uuid");

                    b.HasKey("ParentId", "Identifier");

                    b.HasIndex("DbMangaMangaId");

                    b.ToTable("MangaDownloadExtensionIds", (string)null);
                });

            modelBuilder.Entity("Database.MangaContext.DbChapter", b =>
                {
                    b.HasOne("Database.MangaContext.DbManga", "Manga")
                        .WithMany("Chapters")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("Database.MangaContext.DownloadExtensionId<Database.MangaContext.DbChapter>", b =>
                {
                    b.HasOne("Database.MangaContext.DbChapter", "Parent")
                        .WithMany("DownloadExtensionIds")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Database.MangaContext.DownloadExtensionId<Database.MangaContext.DbManga>", b =>
                {
                    b.HasOne("Database.MangaContext.DbManga", null)
                        .WithMany("DownloadExtensionIds")
                        .HasForeignKey("DbMangaMangaId");

                    b.HasOne("Database.MangaContext.DbManga", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Database.MangaContext.DbChapter", b =>
                {
                    b.Navigation("DownloadExtensionIds");
                });

            modelBuilder.Entity("Database.MangaContext.DbManga", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("DownloadExtensionIds");
                });
#pragma warning restore 612, 618
        }
    }
}
