name: Bug Report
description: File a bug report
title: "[Tranga broke]: <title>"
labels: ["bug"]
body:
- type: textarea
  attributes:
    label: What is broken?
    description: What happened? How did we get here?
    placeholder: Tell me what you expected to happen, and what happened instead.
  validations:
    required: true
- type: textarea
  attributes: 
    label: Log-output
    description: The output of `docker logs tranga-api`
    render: console
- type: textarea
  attributes:
    label: Tranga version
    description: The output of `docker logs tranga-api` should start with `INFO  Startup - LOGO` and `--10/06/2025 13:59:16 for AnyCpu`, paste the output here to check what build you are running
    render: console
- type: textarea
  attributes: 
    label: Additional stuff
    description: Screenshots, anything you think might help