name: New Extension
description: Add a new Extension
title: "[Extension]: <title>"
labels: ["extension"]
body:
- type: textarea
  attributes:
    label: Name
    description: Name of the service
  validations:
    required: true
- type: textarea
  attributes:
    label: Url
    description: Documentation
    placeholder: https://...
  validations:
    required: true