name: New Connector Request
description: Request a new site to be added
title: "[New Connector]: <title>"
labels: ["New Connector"]
body:
  - type: input
    attributes:
      label: Website-Link
      placeholder: https://
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        If you want implement this read [Contributing](https://github.com/C9Glax/tranga#contributing). Thank you!