// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = { baseUrl: `${string}://${string}` | (string & {}) };

export type ContentRating = 'Safe' | 'Suggestive' | 'Erotica' | 'Pornographic';

export type MangaMetadata = {
    metadataExtensionId: string;
    identifier: string;
    url: null | string;
    monitored?: null | boolean;
    mangaId: string;
    series: string;
    summary: null | string;
    year?: null | number | string;
    language?: null | string;
    chaptersNumber?: null | number | string;
    coverId: null | string;
    genres?: Array<string>;
    authors?: Array<string>;
    artists?: Array<string>;
};

export type MatchResult = {
    downloadExtensionId: string;
    identifier: string;
    url: null | string;
    mangaId: string;
    series: string;
    summary: null | string;
    year?: null | number | string;
    language?: null | string;
    chaptersNumber?: null | number | string;
    coverId: null | string;
    genres?: Array<string>;
    authors?: Array<string>;
    artists?: Array<string>;
};

/**
 * The query to use when searching for a Manga
 */
export type SearchQuery = {
    /**
     * The title of the Manga.
     */
    title?: null | string;
    tags?: null | Array<string>;
    contentRating?: null | ContentRating;
    /**
     * The release-year of the Manga
     */
    year?: null | number | string;
    /**
     * An author of the Manga
     */
    author?: null | string;
    /**
     * An artist of the Manga
     */
    artist?: null | string;
    /**
     * The ISO language-code of a translation
     */
    language?: null | string;
    /**
     * The MangaUpdates.com series id
     */
    mangaUpdatesSeriesId?: null | number | string;
};

export type GetMangasData = { body?: never; path?: never; query?: { includeUnmonitored?: boolean }; url: '/mangas' };

export type GetMangasErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetMangasResponses = {
    /**
     * OK
     */
    200: Array<MangaMetadata>;
};

export type GetMangasResponse = GetMangasResponses[keyof GetMangasResponses];

export type GetMangasByMangaIdData = { body?: never; path: { mangaId: string }; query?: never; url: '/mangas/{mangaId}' };

export type GetMangasByMangaIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMangasByMangaIdResponses = {
    /**
     * OK
     */
    200: MangaMetadata;
};

export type GetMangasByMangaIdResponse = GetMangasByMangaIdResponses[keyof GetMangasByMangaIdResponses];

export type GetMangasByMangaIdCoverData = { body?: never; path: { mangaId: string }; query?: never; url: '/mangas/{mangaId}/cover' };

export type GetMangasByMangaIdCoverErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetMangasByMangaIdCoverResponses = {
    /**
     * No Content
     */
    204: void;
};

export type GetMangasByMangaIdCoverResponse = GetMangasByMangaIdCoverResponses[keyof GetMangasByMangaIdCoverResponses];

export type PostMangasSearchData = { body: SearchQuery; path?: never; query?: never; url: '/mangas/search' };

export type PostMangasSearchErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostMangasSearchResponses = {
    /**
     * OK
     */
    200: Array<MangaMetadata>;
};

export type PostMangasSearchResponse = PostMangasSearchResponses[keyof PostMangasSearchResponses];

export type PostMangasByMangaIdMatchData = { body?: never; path: { mangaId: string }; query?: never; url: '/mangas/{mangaId}/match' };

export type PostMangasByMangaIdMatchErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type PostMangasByMangaIdMatchResponses = {
    /**
     * OK
     */
    200: Array<MatchResult>;
};

export type PostMangasByMangaIdMatchResponse = PostMangasByMangaIdMatchResponses[keyof PostMangasByMangaIdMatchResponses];
