// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = { baseUrl: `${string}://${string}` | (string & {}) };

export type ContentRating = 'Safe' | 'Suggestive' | 'Erotica' | 'Pornographic';

export type Manga = { mangaId: string; monitored: boolean; metadataEntry?: null | MangaMetadata };

export type MangaMetadata = {
    metadataId: string;
    metadataExtensionId: string;
    identifier: string;
    chosen?: null | boolean;
    series: string;
    summary: null | string;
    year?: null | number | string;
    language?: null | string;
    chaptersNumber?: null | number | string;
    coverId: null | string;
    genres?: Array<string>;
    authors?: Array<string>;
    artists?: Array<string>;
    url: null | string;
};

export type MetadataManga = {
    mangaIds: Array<string>;
    metadataId: string;
    metadataExtensionId: string;
    identifier: string;
    chosen?: null | boolean;
    series: string;
    summary: null | string;
    year?: null | number | string;
    language?: null | string;
    chaptersNumber?: null | number | string;
    coverId: null | string;
    genres?: Array<string>;
    authors?: Array<string>;
    artists?: Array<string>;
    url: null | string;
};

export type PatchMangaMetadataEntryRequest = { metadataId: string };

/**
 * The query to use when searching for a Manga
 */
export type SearchQuery = {
    /**
     * The title of the Manga.
     */
    title?: null | string;
    tags?: null | Array<string>;
    contentRating?: null | ContentRating;
    /**
     * The release-year of the Manga
     */
    year?: null | number | string;
    /**
     * An author of the Manga
     */
    author?: null | string;
    /**
     * An artist of the Manga
     */
    artist?: null | string;
    /**
     * The ISO language-code of a translation
     */
    language?: null | string;
    /**
     * The MangaUpdates.com series id
     */
    mangaUpdatesSeriesId?: null | number | string;
};

export type GetMangasData = { body?: never; path?: never; query?: never; url: '/mangas' };

export type GetMangasErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetMangasResponses = {
    /**
     * OK
     */
    200: Array<Manga>;
};

export type GetMangasResponse = GetMangasResponses[keyof GetMangasResponses];

export type GetMangasByMangaIdData = { body?: never; path: { mangaId: string }; query?: never; url: '/mangas/{mangaId}' };

export type GetMangasByMangaIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMangasByMangaIdResponses = {
    /**
     * OK
     */
    200: Manga;
};

export type GetMangasByMangaIdResponse = GetMangasByMangaIdResponses[keyof GetMangasByMangaIdResponses];

export type GetMangasByMangaIdCoverData = { body?: never; path: { mangaId: string }; query?: never; url: '/mangas/{mangaId}/cover' };

export type GetMangasByMangaIdCoverErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetMangasByMangaIdCoverResponses = {
    /**
     * No Content
     */
    204: void;
};

export type GetMangasByMangaIdCoverResponse = GetMangasByMangaIdCoverResponses[keyof GetMangasByMangaIdCoverResponses];

export type PostMangasSearchData = { body: SearchQuery; path?: never; query?: never; url: '/mangas/search' };

export type PostMangasSearchErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostMangasSearchResponses = {
    /**
     * OK
     */
    200: Array<MangaMetadata>;
};

export type PostMangasSearchResponse = PostMangasSearchResponses[keyof PostMangasSearchResponses];

export type PatchMangasByMangaIdUseMetadataData = {
    body: PatchMangaMetadataEntryRequest;
    path: { mangaId: string };
    query?: never;
    url: '/mangas/{mangaId}/useMetadata';
};

export type PatchMangasByMangaIdUseMetadataErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type PatchMangasByMangaIdUseMetadataResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetMetadataData = { body?: never; path?: never; query?: never; url: '/metadata' };

export type GetMetadataErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetMetadataResponses = {
    /**
     * OK
     */
    200: Array<MetadataManga>;
};

export type GetMetadataResponse = GetMetadataResponses[keyof GetMetadataResponses];

export type GetMetadataByMetadataIdData = { body?: never; path: { metadataId: string }; query?: never; url: '/metadata/{metadataId}' };

export type GetMetadataByMetadataIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMetadataByMetadataIdResponses = {
    /**
     * OK
     */
    200: MetadataManga;
};

export type GetMetadataByMetadataIdResponse = GetMetadataByMetadataIdResponses[keyof GetMetadataByMetadataIdResponses];

export type GetFilesByFileIdData = { body?: never; path: { fileId: string }; query?: never; url: '/files/{fileId}' };

export type GetFilesByFileIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};
