// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/mini';

export const zContentRating = z.enum(['Safe', 'Suggestive', 'Erotica', 'Pornographic']);

export type ContentRatingZodType = z.infer<typeof zContentRating>;

export const zMangaMetadata = z.object({
    metadataExtensionId: z.uuid(),
    identifier: z.string(),
    url: z.nullable(z.string()),
    monitored: z.nullish(z.boolean()),
    mangaId: z.uuid(),
    series: z.string().check(z.minLength(0), z.maxLength(1024)),
    summary: z.nullable(z.string().check(z.minLength(0), z.maxLength(4096))),
    year: z.nullish(
        z.union([
            z
                .int()
                .check(
                    z.minimum(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }),
                    z.maximum(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
                ),
            z.string().check(z.regex(/^-?(?:0|[1-9]\d*)$/)),
        ])
    ),
    language: z.nullish(z.string().check(z.minLength(0), z.maxLength(8))),
    chaptersNumber: z.nullish(
        z.union([
            z
                .int()
                .check(
                    z.minimum(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }),
                    z.maximum(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
                ),
            z.string().check(z.regex(/^-?(?:0|[1-9]\d*)$/)),
        ])
    ),
    coverId: z.nullable(z.uuid()),
    genres: z.optional(z.array(z.string())),
    authors: z.optional(z.array(z.string())),
    artists: z.optional(z.array(z.string())),
});

export type MangaMetadataZodType = z.infer<typeof zMangaMetadata>;

export const zMatchResult = z.object({
    downloadExtensionId: z.uuid(),
    identifier: z.string(),
    url: z.nullable(z.string()),
    mangaId: z.uuid(),
    series: z.string().check(z.minLength(0), z.maxLength(1024)),
    summary: z.nullable(z.string().check(z.minLength(0), z.maxLength(4096))),
    year: z.nullish(
        z.union([
            z
                .int()
                .check(
                    z.minimum(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }),
                    z.maximum(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
                ),
            z.string().check(z.regex(/^-?(?:0|[1-9]\d*)$/)),
        ])
    ),
    language: z.nullish(z.string().check(z.minLength(0), z.maxLength(8))),
    chaptersNumber: z.nullish(
        z.union([
            z
                .int()
                .check(
                    z.minimum(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }),
                    z.maximum(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
                ),
            z.string().check(z.regex(/^-?(?:0|[1-9]\d*)$/)),
        ])
    ),
    coverId: z.nullable(z.uuid()),
    genres: z.optional(z.array(z.string())),
    authors: z.optional(z.array(z.string())),
    artists: z.optional(z.array(z.string())),
});

export type MatchResultZodType = z.infer<typeof zMatchResult>;

/**
 * The query to use when searching for a Manga
 */
export const zSearchQuery = z.object({
    title: z.nullish(z.string()),
    tags: z.nullish(z.array(z.string())),
    contentRating: z.nullish(zContentRating),
    year: z.nullish(
        z.union([
            z
                .int()
                .check(
                    z.minimum(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }),
                    z.maximum(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
                ),
            z.string().check(z.regex(/^-?(?:0|[1-9]\d*)$/)),
        ])
    ),
    author: z.nullish(z.string()),
    artist: z.nullish(z.string()),
    language: z.nullish(z.string()),
    mangaUpdatesSeriesId: z.nullish(
        z.union([
            z.coerce
                .bigint()
                .check(
                    z.minimum(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }),
                    z.maximum(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
                ),
            z.coerce
                .bigint()
                .check(
                    z.minimum(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }),
                    z.maximum(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
                ),
        ])
    ),
});

export type SearchQueryZodType = z.infer<typeof zSearchQuery>;
