// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = { baseUrl: `${string}://${string}` | (string & {}) };

export type ServicesMangaChapter = {
    chapterId: string;
    mangaId: string;
    title: null | string;
    volume: null | string;
    number: string;
    releaseDate: null | string;
};

export type ServicesMangaContentRating = 'Safe' | 'Suggestive' | 'Erotica' | 'Pornographic';

export type ServicesMangaDownloadExtension = { downloadExtensionsId: string; name: string; iconUrl: string; isSuwayomiSource: boolean };

export type ServicesMangaDownloadExtensionsList = { extensions?: Array<ServicesMangaDownloadExtension> };

export type ServicesMangaDownloadLink = {
    downloadId: string;
    downloadExtensionId: string;
    identifier: string;
    series: string;
    summary: null | string;
    language?: null | string;
    url: null | string;
    coverId: null | string;
    nsfw: null | boolean;
};

export type ServicesMangaManga = {
    mangaId: string;
    monitored: boolean;
    metadataEntry?: null | ServicesMangaMetadata;
    downloadLinks?: null | Array<ServicesMangaDownloadLink>;
};

export type ServicesMangaMangaChapter = {
    isDownloaded: boolean;
    chapterId: string;
    mangaId: string;
    title: null | string;
    volume: null | string;
    number: string;
    releaseDate: null | string;
};

export type ServicesMangaMangaDownloadLink = {
    mangaId: string;
    matched: boolean;
    priority: number | string;
    language?: null | string;
    downloadId: string;
    downloadExtensionId: string;
    identifier: string;
    series: string;
    summary: null | string;
    url: null | string;
    coverId: null | string;
    nsfw: null | boolean;
};

export type ServicesMangaMetadata = {
    metadataId: string;
    metadataExtensionId: string;
    identifier: string;
    chosen?: null | boolean;
    series: string;
    summary: null | string;
    year?: null | number | string;
    language?: null | string;
    chaptersNumber?: null | number | string;
    coverId: null | string;
    genres?: Array<string>;
    authors?: Array<string>;
    artists?: Array<string>;
    url: null | string;
    status?: null | ServicesMangaReleaseStatus;
    nsfw: null | boolean;
};

export type ServicesMangaMetadataExtension = { metadataExtensionId: string; name: string; iconUrl: string };

export type ServicesMangaMetadataExtensionsList = { extensions?: Array<ServicesMangaMetadataExtension> };

export type ServicesMangaPatchMangaDownloadLinkRequest = { matched: boolean; priority: number | string };

export type ServicesMangaPatchMangaMonitoredRequest = { monitored: boolean };

export type ServicesMangaPostMangaDownloadLinkRequest = { downloadExtensionId: string; url: string };

export type ServicesMangaPostMangaMergeRequest = { sourceMangaId: string; keepSourceMetadata: boolean; keepSourceChapters: boolean };

export type ServicesMangaPostSearchMangaDownloadLinksRequest = { searchTerm: null | string };

export type ServicesMangaPostSearchMangaRequest = { searchQuery: ServicesMangaSearchQuery; metadataExtensionIds: null | Array<string> };

export type ServicesMangaReleaseStatus = 'Ongoing' | 'Complete' | 'Hiatus' | 'Cancelled';

export type ServicesMangaSearchQuery = {
    title?: null | string;
    tags?: null | Array<string>;
    contentRating?: null | ServicesMangaContentRating;
    year?: null | number | string;
    author?: null | string;
    artist?: null | string;
    language?: null | string;
    mangaUpdatesSeriesId?: null | number | string;
    mangaDexSeriesId?: null | string;
};

/**
 *             How a Suwayomi source or extension is classified by its extension store.
 * Suwayomi also exposes a deprecated isNsfw boolean, but that collapses SuwayomiContentWarning.Mixed into
 * SuwayomiContentWarning.Nsfw — which would wrongly lock out sites that merely allow adult content alongside everything else
 * (MangaDex and Weeb Central are both SuwayomiContentWarning.Mixed).
 */
export type ServicesMangaSuwayomiContentWarning = 'Safe' | 'Mixed' | 'Nsfw';

/**
 * An extension offered by, or installed from, a configured extension store.
 */
export type ServicesMangaSuwayomiExtensionInfo = {
    /**
     * Android package name; the identifier used to install, update and uninstall.
     */
    pkgName: string;
    /**
     * Display name of the extension.
     */
    name: string;
    /**
     * Tachiyomi language code, e.g. `en`, `pt-BR`, `all`.
     */
    lang: string;
    /**
     * Gateway-relative url of the extension's icon.
     */
    iconUrl: string;
    /**
     * Version currently installed, or offered by the store when not installed.
     */
    versionName: string;
    /**
     * How the extension store classifies the content. A `Mixed` extension stays usable while `AllowNSFW` is off; only `Nsfw` ones are held back.
     */
    contentWarning: ServicesMangaSuwayomiContentWarning;
    /**
     * Whether the extension is installed on the sidecar.
     */
    isInstalled: boolean;
    /**
     * Whether the extension is no longer offered by any configured store.
     */
    isObsolete: boolean;
    /**
     * Whether a newer version is available.
     */
    hasUpdate: boolean;
};

/**
 * A source exposed by an installed extension, and the Tranga download-extension it is registered as.
 */
export type ServicesMangaSuwayomiSourceInfo = {
    /**
     * The Tachiyomi source id.
     */
    sourceId: string;
    /**
     * The Tranga extension identifier derived from SourceId.
     */
    extensionId: string;
    /**
     * Display name of the source, normally including its language.
     */
    name: string;
    /**
     * Tachiyomi language code.
     */
    lang: string;
    /**
     * Gateway-relative url of the source's icon.
     */
    iconUrl: string;
    /**
     * The source's own website.
     */
    homeUrl: string;
    /**
     * How the extension store classifies the source's content.
     */
    contentWarning: ServicesMangaSuwayomiContentWarning;
};

/**
 * Reachability and version of the Suwayomi sidecar.
 */
export type ServicesMangaSuwayomiStatus = {
    /**
     * Whether the sidecar answered. False means the container is missing or still starting.
     */
    reachable: boolean;
    /**
     * Sidecar product name, when reachable.
     */
    serverName: null | string;
    /**
     * Sidecar version, when reachable.
     */
    serverVersion: null | string;
    /**
     * Number of sources currently exposed by installed extensions.
     */
    installedSourceCount: number | string;
};

export type ServicesTasksChapterSummary = {
    chapterId: string;
    mangaId: string;
    title?: null | string;
    volume?: null | string;
    number: string;
};

export type ServicesTasksMangaSummary = { mangaId: string; series?: null | string };

export type ServicesTasksTask =
    | ({ kind?: 'Services_Tasks_TaskTask' } & ServicesTasksTaskTask)
    | ({ kind?: 'Services_Tasks_TaskMangaTask' } & ServicesTasksTaskMangaTask)
    | ({ kind?: 'Services_Tasks_TaskChapterTask' } & ServicesTasksTaskChapterTask);

export type ServicesTasksTaskChapterTask = {
    kind?: 'chapterTask';
    chapter: ServicesTasksChapterSummary;
    manga: ServicesTasksMangaSummary;
    taskId: string;
    taskTypeId: string;
    taskTypeName: string;
    taskType: ServicesTasksTaskType;
    lastRun: null | string;
    status: ServicesTasksTaskState;
    interval?: null | string;
};

export type ServicesTasksTaskLogEntry = { timestamp: string; level: string; message: string };

export type ServicesTasksTaskMangaTask = {
    kind?: 'mangaTask';
    manga: ServicesTasksMangaSummary;
    taskId: string;
    taskTypeId: string;
    taskTypeName: string;
    taskType: ServicesTasksTaskType;
    lastRun: null | string;
    status: ServicesTasksTaskState;
    interval?: null | string;
};

export type ServicesTasksTaskState = 'Pending' | 'Blocked' | 'Queued' | 'Running' | 'Completed' | 'Failed';

export type ServicesTasksTaskTask = {
    kind?: 'task';
    taskId: string;
    taskTypeId: string;
    taskTypeName: string;
    taskType: ServicesTasksTaskType;
    lastRun: null | string;
    status: ServicesTasksTaskState;
    interval?: null | string;
};

export type ServicesTasksTaskType = 'PeriodicTask' | 'RunOnceTask';

export type ServicesTasksWorker = {
    workerId: string;
    status: ServicesTasksWorkerStatus;
    currentTaskId?: null | string;
    currentTaskTypeId?: null | string;
    startedAt: string;
    lastHeartbeat: string;
};

export type ServicesTasksWorkerStatus = 'Idle' | 'Busy' | 'Retiring';

export type ServicesNotificationsNotificationExtension = { id: string; name: string; type: ServicesNotificationsNotificationExtensionType };

export type ServicesNotificationsNotificationExtensionType = 'Naprise' | 'Discord' | 'Gotify' | 'NtfySh' | 'Telegram';

export type ServicesNotificationsPutExtensionRequest = { name?: string };

export type ServicesNotificationsPutExtensionRequestDiscord = { webhookId: string; webhookToken: string; name: string };

export type ServicesNotificationsPutExtensionRequestGotify = { host: string; port: number | string; appToken: string; name: string };

export type ServicesNotificationsPutExtensionRequestNapriseServiceUrl = { serviceUrl: string; name: string };

export type ServicesNotificationsPutExtensionRequestNtfySh = {
    host: string;
    port: number | string;
    topic: string;
    user?: null | string;
    password?: null | string;
    name: string;
};

export type ServicesNotificationsPutExtensionRequestTelegram = { token: string; chatId: string; name: string };

export type ServicesLibrariesAddKomgaLibraryRequest = {
    name: string;
    baseUrl: string;
    apiKey?: null | string;
    username?: null | string;
    password?: null | string;
    libraryRootPath?: null | string;
};

export type ServicesLibrariesLibrary = {
    libraryServiceType: ServicesLibrariesLibraryServiceType;
    id: string;
    name: string;
    baseUrl: string;
};

export type ServicesLibrariesLibraryMangaLink = { libraryServiceId: string; seriesUrl: string };

export type ServicesLibrariesLibraryServiceType = 'Komga';

export type ServicesLibrariesPatchLibraryRequest = {
    name?: null | string;
    apiKey?: null | string;
    username?: null | string;
    password?: null | string;
};

export type ServicesLibrariesTestKomgaConnectionRequest = {
    baseUrl: string;
    apiKey?: null | string;
    username?: null | string;
    password?: null | string;
};

export type ServicesAuthApiKeyResponse = {
    id: string;
    name: null | string;
    scope: ServicesAuthApiKeyScope;
    createdAt: string;
    lastUsedAt: null | string;
};

export type ServicesAuthApiKeyScope = 'All';

export type ServicesAuthAuthStatusResponse = { enabled: boolean; configured: boolean };

export type ServicesAuthAuthTokenResponse = { token: string };

export type ServicesAuthCreateApiKeyRequest = { name: null | string; scope?: ServicesAuthApiKeyScope };

export type ServicesAuthCreateApiKeyResponse = {
    id: string;
    key: string;
    name: null | string;
    scope: ServicesAuthApiKeyScope;
    createdAt: string;
};

export type ServicesAuthSetupRequest = { password: string };

export type GetMangasData = { body?: never; path?: never; query?: never; url: '/mangas' };

export type GetMangasErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetMangasResponses = {
    /**
     * OK
     */
    200: Array<ServicesMangaManga>;
};

export type GetMangasResponse = GetMangasResponses[keyof GetMangasResponses];

export type GetMangasByMangaIdData = { body?: never; path: { mangaId: string }; query?: never; url: '/mangas/{mangaId}' };

export type GetMangasByMangaIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMangasByMangaIdResponses = {
    /**
     * OK
     */
    200: ServicesMangaManga;
};

export type GetMangasByMangaIdResponse = GetMangasByMangaIdResponses[keyof GetMangasByMangaIdResponses];

export type GetMangasByMangaIdCoverData = {
    body?: never;
    path: { mangaId: string };
    query?: { width?: number | string; height?: number | string };
    url: '/mangas/{mangaId}/cover';
};

export type GetMangasByMangaIdCoverErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetMangasByMangaIdCoverResponses = {
    /**
     * No Content
     */
    204: void;
};

export type GetMangasByMangaIdCoverResponse = GetMangasByMangaIdCoverResponses[keyof GetMangasByMangaIdCoverResponses];

export type GetMangasByMangaIdMetadataData = { body?: never; path: { mangaId: string }; query?: never; url: '/mangas/{mangaId}/metadata' };

export type GetMangasByMangaIdMetadataErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMangasByMangaIdMetadataResponses = {
    /**
     * OK
     */
    200: ServicesMangaMetadata;
};

export type GetMangasByMangaIdMetadataResponse = GetMangasByMangaIdMetadataResponses[keyof GetMangasByMangaIdMetadataResponses];

export type GetMangasByMangaIdMetadataRelatedData = {
    body?: never;
    path: { mangaId: string };
    query?: never;
    url: '/mangas/{mangaId}/metadata/related';
};

export type GetMangasByMangaIdMetadataRelatedErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMangasByMangaIdMetadataRelatedResponses = {
    /**
     * OK
     */
    200: Array<ServicesMangaMetadata>;
};

export type GetMangasByMangaIdMetadataRelatedResponse =
    GetMangasByMangaIdMetadataRelatedResponses[keyof GetMangasByMangaIdMetadataRelatedResponses];

export type PatchMangasByMangaIdMetadataByMetadataIdData = {
    body?: never;
    path: { mangaId: string; metadataId: string };
    query?: never;
    url: '/mangas/{mangaId}/metadata/{metadataId}';
};

export type PatchMangasByMangaIdMetadataByMetadataIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type PatchMangasByMangaIdMetadataByMetadataIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchMangasByMangaIdMonitoredData = {
    body: ServicesMangaPatchMangaMonitoredRequest;
    path: { mangaId: string };
    query?: never;
    url: '/mangas/{mangaId}/monitored';
};

export type PatchMangasByMangaIdMonitoredErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type PatchMangasByMangaIdMonitoredResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostMangasByMangaIdSyncData = { body?: never; path: { mangaId: string }; query?: never; url: '/mangas/{mangaId}/sync' };

export type PostMangasByMangaIdSyncErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type PostMangasByMangaIdSyncResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostMangasByMangaIdRemoveData = { body?: never; path: { mangaId: string }; query?: never; url: '/mangas/{mangaId}/remove' };

export type PostMangasByMangaIdRemoveErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type PostMangasByMangaIdRemoveResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostMangasByMangaIdMergeData = {
    body: ServicesMangaPostMangaMergeRequest;
    path: { mangaId: string };
    query?: never;
    url: '/mangas/{mangaId}/merge';
};

export type PostMangasByMangaIdMergeErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostMangasByMangaIdMergeError = PostMangasByMangaIdMergeErrors[keyof PostMangasByMangaIdMergeErrors];

export type PostMangasByMangaIdMergeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetMangasByMangaIdChaptersData = { body?: never; path: { mangaId: string }; query?: never; url: '/mangas/{mangaId}/chapters' };

export type GetMangasByMangaIdChaptersResponses = {
    /**
     * OK
     */
    200: Array<ServicesMangaMangaChapter>;
};

export type GetMangasByMangaIdChaptersResponse = GetMangasByMangaIdChaptersResponses[keyof GetMangasByMangaIdChaptersResponses];

export type GetMangasByMangaIdDownloadLinksData = {
    body?: never;
    path: { mangaId: string };
    query?: never;
    url: '/mangas/{mangaId}/downloadLinks';
};

export type GetMangasByMangaIdDownloadLinksErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMangasByMangaIdDownloadLinksResponses = {
    /**
     * OK
     */
    200: Array<ServicesMangaMangaDownloadLink>;
};

export type GetMangasByMangaIdDownloadLinksResponse =
    GetMangasByMangaIdDownloadLinksResponses[keyof GetMangasByMangaIdDownloadLinksResponses];

export type PostMangasByMangaIdDownloadLinksData = {
    body: ServicesMangaPostMangaDownloadLinkRequest;
    path: { mangaId: string };
    query?: never;
    url: '/mangas/{mangaId}/downloadLinks';
};

export type PostMangasByMangaIdDownloadLinksErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostMangasByMangaIdDownloadLinksError = PostMangasByMangaIdDownloadLinksErrors[keyof PostMangasByMangaIdDownloadLinksErrors];

export type PostMangasByMangaIdDownloadLinksResponses = {
    /**
     * OK
     */
    200: ServicesMangaMangaDownloadLink;
};

export type PostMangasByMangaIdDownloadLinksResponse =
    PostMangasByMangaIdDownloadLinksResponses[keyof PostMangasByMangaIdDownloadLinksResponses];

export type PatchMangasByMangaIdDownloadLinksByDownloadIdData = {
    body: ServicesMangaPatchMangaDownloadLinkRequest;
    path: { mangaId: string; downloadId: string };
    query?: never;
    url: '/mangas/{mangaId}/downloadLinks/{downloadId}';
};

export type PatchMangasByMangaIdDownloadLinksByDownloadIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type PatchMangasByMangaIdDownloadLinksByDownloadIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostMangasSearchData = { body: ServicesMangaPostSearchMangaRequest; path?: never; query?: never; url: '/mangas/search' };

export type PostMangasSearchErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostMangasSearchResponses = {
    /**
     * OK
     */
    200: Array<ServicesMangaMetadata>;
};

export type PostMangasSearchResponse = PostMangasSearchResponses[keyof PostMangasSearchResponses];

export type PostMangasSearchByMangaIdDownloadLinksData = {
    body?: null | ServicesMangaPostSearchMangaDownloadLinksRequest;
    path: { mangaId: string };
    query?: never;
    url: '/mangas/search/{mangaId}/downloadLinks';
};

export type PostMangasSearchByMangaIdDownloadLinksErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostMangasSearchByMangaIdDownloadLinksResponses = {
    /**
     * OK
     */
    200: Array<ServicesMangaMangaDownloadLink>;
};

export type PostMangasSearchByMangaIdDownloadLinksResponse =
    PostMangasSearchByMangaIdDownloadLinksResponses[keyof PostMangasSearchByMangaIdDownloadLinksResponses];

export type GetMangasChaptersData = { body: Array<string>; path?: never; query?: never; url: '/mangas/chapters' };

export type GetMangasChaptersResponses = {
    /**
     * OK
     */
    200: Array<ServicesMangaChapter>;
};

export type GetMangasChaptersResponse = GetMangasChaptersResponses[keyof GetMangasChaptersResponses];

export type GetMangasChaptersByChapterIdData = {
    body?: never;
    path: { chapterId: string };
    query?: never;
    url: '/mangas/chapters/{chapterId}';
};

export type GetMangasChaptersByChapterIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMangasChaptersByChapterIdResponses = {
    /**
     * OK
     */
    200: ServicesMangaChapter;
};

export type GetMangasChaptersByChapterIdResponse = GetMangasChaptersByChapterIdResponses[keyof GetMangasChaptersByChapterIdResponses];

export type GetMangasMetadataExtensionsData = { body?: never; path?: never; query?: never; url: '/mangas/metadata/extensions' };

export type GetMangasMetadataExtensionsResponses = {
    /**
     * OK
     */
    200: ServicesMangaMetadataExtensionsList;
};

export type GetMangasMetadataExtensionsResponse = GetMangasMetadataExtensionsResponses[keyof GetMangasMetadataExtensionsResponses];

export type GetMangasMetadataData = { body?: never; path?: never; query?: never; url: '/mangas/metadata' };

export type GetMangasMetadataErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetMangasMetadataResponses = {
    /**
     * OK
     */
    200: Array<ServicesMangaMetadata>;
};

export type GetMangasMetadataResponse = GetMangasMetadataResponses[keyof GetMangasMetadataResponses];

export type GetMangasMetadataByMetadataIdData = {
    body?: never;
    path: { metadataId: string };
    query?: never;
    url: '/mangas/metadata/{metadataId}';
};

export type GetMangasMetadataByMetadataIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMangasMetadataByMetadataIdResponses = {
    /**
     * OK
     */
    200: ServicesMangaMetadata;
};

export type GetMangasMetadataByMetadataIdResponse = GetMangasMetadataByMetadataIdResponses[keyof GetMangasMetadataByMetadataIdResponses];

export type GetMangasMetadataByMetadataIdMangaData = {
    body?: never;
    path: { metadataId: string };
    query?: never;
    url: '/mangas/metadata/{metadataId}/manga';
};

export type GetMangasMetadataByMetadataIdMangaErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMangasMetadataByMetadataIdMangaResponses = {
    /**
     * OK
     */
    200: ServicesMangaManga;
};

export type GetMangasMetadataByMetadataIdMangaResponse =
    GetMangasMetadataByMetadataIdMangaResponses[keyof GetMangasMetadataByMetadataIdMangaResponses];

export type GetMangasMetadataByMetadataIdMangaRelatedData = {
    body?: never;
    path: { metadataId: string };
    query?: never;
    url: '/mangas/metadata/{metadataId}/manga/related';
};

export type GetMangasMetadataByMetadataIdMangaRelatedErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMangasMetadataByMetadataIdMangaRelatedResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetMangasMetadataByMetadataIdMangaRelatedResponse =
    GetMangasMetadataByMetadataIdMangaRelatedResponses[keyof GetMangasMetadataByMetadataIdMangaRelatedResponses];

export type GetMangasDownloadLinksExtensionsData = { body?: never; path?: never; query?: never; url: '/mangas/downloadLinks/extensions' };

export type GetMangasDownloadLinksExtensionsResponses = {
    /**
     * OK
     */
    200: ServicesMangaDownloadExtensionsList;
};

export type GetMangasDownloadLinksExtensionsResponse =
    GetMangasDownloadLinksExtensionsResponses[keyof GetMangasDownloadLinksExtensionsResponses];

export type GetMangasDownloadLinksData = { body?: never; path?: never; query?: never; url: '/mangas/downloadLinks' };

export type GetMangasDownloadLinksErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetMangasDownloadLinksResponses = {
    /**
     * OK
     */
    200: Array<ServicesMangaMangaDownloadLink>;
};

export type GetMangasDownloadLinksResponse = GetMangasDownloadLinksResponses[keyof GetMangasDownloadLinksResponses];

export type GetMangasDownloadLinksByDownloadIdData = {
    body?: never;
    path: { downloadId: string };
    query?: never;
    url: '/mangas/downloadLinks/{downloadId}';
};

export type GetMangasDownloadLinksByDownloadIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMangasDownloadLinksByDownloadIdResponses = {
    /**
     * OK
     */
    200: ServicesMangaDownloadLink;
};

export type GetMangasDownloadLinksByDownloadIdResponse =
    GetMangasDownloadLinksByDownloadIdResponses[keyof GetMangasDownloadLinksByDownloadIdResponses];

export type GetMangasFilesByFileIdData = {
    body?: never;
    path: { fileId: string };
    query?: { width?: number | string; height?: number | string };
    url: '/mangas/files/{fileId}';
};

export type GetMangasFilesByFileIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetMangasSuwayomiStatusData = { body?: never; path?: never; query?: never; url: '/mangas/suwayomi/status' };

export type GetMangasSuwayomiStatusResponses = {
    /**
     * OK
     */
    200: ServicesMangaSuwayomiStatus;
};

export type GetMangasSuwayomiStatusResponse = GetMangasSuwayomiStatusResponses[keyof GetMangasSuwayomiStatusResponses];

export type GetMangasSuwayomiExtensionsData = {
    body?: never;
    path?: never;
    query?: { refresh?: boolean };
    url: '/mangas/suwayomi/extensions';
};

export type GetMangasSuwayomiExtensionsResponses = {
    /**
     * OK
     */
    200: Array<ServicesMangaSuwayomiExtensionInfo>;
};

export type GetMangasSuwayomiExtensionsResponse = GetMangasSuwayomiExtensionsResponses[keyof GetMangasSuwayomiExtensionsResponses];

export type PostMangasSuwayomiExtensionsByPkgNameInstallData = {
    body?: never;
    path: { pkgName: string };
    query?: never;
    url: '/mangas/suwayomi/extensions/{pkgName}/install';
};

export type PostMangasSuwayomiExtensionsByPkgNameInstallResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostMangasSuwayomiExtensionsByPkgNameUpdateData = {
    body?: never;
    path: { pkgName: string };
    query?: never;
    url: '/mangas/suwayomi/extensions/{pkgName}/update';
};

export type PostMangasSuwayomiExtensionsByPkgNameUpdateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteMangasSuwayomiExtensionsByPkgNameData = {
    body?: never;
    path: { pkgName: string };
    query?: never;
    url: '/mangas/suwayomi/extensions/{pkgName}';
};

export type DeleteMangasSuwayomiExtensionsByPkgNameResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetMangasSuwayomiSourcesData = { body?: never; path?: never; query?: never; url: '/mangas/suwayomi/sources' };

export type GetMangasSuwayomiSourcesResponses = {
    /**
     * OK
     */
    200: Array<ServicesMangaSuwayomiSourceInfo>;
};

export type GetMangasSuwayomiSourcesResponse = GetMangasSuwayomiSourcesResponses[keyof GetMangasSuwayomiSourcesResponses];

export type PostMangasSuwayomiRefreshData = { body?: never; path?: never; query?: never; url: '/mangas/suwayomi/refresh' };

export type PostMangasSuwayomiRefreshResponses = {
    /**
     * OK
     */
    200: number | string;
};

export type PostMangasSuwayomiRefreshResponse = PostMangasSuwayomiRefreshResponses[keyof PostMangasSuwayomiRefreshResponses];

export type GetTasksData = {
    body?: never;
    path?: never;
    query?: {
        includeFinished?: boolean;
        mangaId?: string;
        taskTypeName?: Array<string>;
        status?: Array<ServicesTasksTaskState>;
        skip?: number | string;
        limit?: number | string;
    };
    url: '/tasks';
};

export type GetTasksResponses = {
    /**
     * OK
     */
    200: Array<ServicesTasksTask>;
};

export type GetTasksResponse = GetTasksResponses[keyof GetTasksResponses];

export type GetTasksWorkersData = { body?: never; path?: never; query?: never; url: '/tasks/workers' };

export type GetTasksWorkersResponses = {
    /**
     * OK
     */
    200: Array<ServicesTasksWorker>;
};

export type GetTasksWorkersResponse = GetTasksWorkersResponses[keyof GetTasksWorkersResponses];

export type GetTasksByTaskIdData = { body?: never; path: { taskId: string }; query?: never; url: '/tasks/{taskId}' };

export type GetTasksByTaskIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetTasksByTaskIdResponses = {
    /**
     * OK
     */
    200: ServicesTasksTask;
};

export type GetTasksByTaskIdResponse = GetTasksByTaskIdResponses[keyof GetTasksByTaskIdResponses];

export type GetTasksByTaskIdLogsData = {
    body?: never;
    path: { taskId: string };
    query?: { skip?: number | string; limit?: number | string };
    url: '/tasks/{taskId}/logs';
};

export type GetTasksByTaskIdLogsErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetTasksByTaskIdLogsResponses = {
    /**
     * OK
     */
    200: Array<ServicesTasksTaskLogEntry>;
};

export type GetTasksByTaskIdLogsResponse = GetTasksByTaskIdLogsResponses[keyof GetTasksByTaskIdLogsResponses];

export type PutTasksCreateGetMangaChaptersByMangaIdData = {
    body?: never;
    path: { mangaId: string };
    query?: never;
    url: '/tasks/create/getMangaChapters/{mangaId}';
};

export type PutTasksCreateGetMangaChaptersByMangaIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PutTasksCreateGetMangaChaptersByMangaIdResponses = {
    /**
     * OK
     */
    200: ServicesTasksTask;
};

export type PutTasksCreateGetMangaChaptersByMangaIdResponse =
    PutTasksCreateGetMangaChaptersByMangaIdResponses[keyof PutTasksCreateGetMangaChaptersByMangaIdResponses];

export type GetTasksMangaByMangaIdData = {
    body?: never;
    path: { mangaId: string };
    query?: { includeFinished?: boolean };
    url: '/tasks/manga/{mangaId}';
};

export type GetTasksMangaByMangaIdResponses = {
    /**
     * OK
     */
    200: Array<ServicesTasksTask>;
};

export type GetTasksMangaByMangaIdResponse = GetTasksMangaByMangaIdResponses[keyof GetTasksMangaByMangaIdResponses];

export type GetTasksMangaByMangaIdDownloadsData = {
    body?: never;
    path: { mangaId: string };
    query?: { includeFinished?: boolean };
    url: '/tasks/manga/{mangaId}/downloads';
};

export type GetTasksMangaByMangaIdDownloadsResponses = {
    /**
     * OK
     */
    200: Array<ServicesTasksTask>;
};

export type GetTasksMangaByMangaIdDownloadsResponse =
    GetTasksMangaByMangaIdDownloadsResponses[keyof GetTasksMangaByMangaIdDownloadsResponses];

export type GetTasksMangaDownloadsData = {
    body?: never;
    path?: never;
    query?: { includeFinished?: boolean };
    url: '/tasks/manga/downloads';
};

export type GetTasksMangaDownloadsResponses = {
    /**
     * OK
     */
    200: Array<ServicesTasksTask>;
};

export type GetTasksMangaDownloadsResponse = GetTasksMangaDownloadsResponses[keyof GetTasksMangaDownloadsResponses];

export type GetNotificationsExtensionsData = { body?: never; path?: never; query?: never; url: '/notifications/extensions' };

export type GetNotificationsExtensionsResponses = {
    /**
     * OK
     */
    200: Array<ServicesNotificationsNotificationExtension>;
};

export type GetNotificationsExtensionsResponse = GetNotificationsExtensionsResponses[keyof GetNotificationsExtensionsResponses];

export type PutNotificationsExtensionsData = {
    body: ServicesNotificationsPutExtensionRequest;
    path?: never;
    query?: never;
    url: '/notifications/extensions';
};

export type PutNotificationsExtensionsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PutNotificationsExtensionsResponses = {
    /**
     * OK
     */
    200: ServicesNotificationsNotificationExtension;
};

export type PutNotificationsExtensionsResponse = PutNotificationsExtensionsResponses[keyof PutNotificationsExtensionsResponses];

export type PutNotificationsExtensionsNapriseData = {
    body: ServicesNotificationsPutExtensionRequestNapriseServiceUrl;
    path?: never;
    query?: never;
    url: '/notifications/extensions/naprise';
};

export type PutNotificationsExtensionsNapriseErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PutNotificationsExtensionsNapriseResponses = {
    /**
     * OK
     */
    200: ServicesNotificationsNotificationExtension;
};

export type PutNotificationsExtensionsNapriseResponse =
    PutNotificationsExtensionsNapriseResponses[keyof PutNotificationsExtensionsNapriseResponses];

export type PutNotificationsExtensionsDiscordData = {
    body: ServicesNotificationsPutExtensionRequestDiscord;
    path?: never;
    query?: never;
    url: '/notifications/extensions/discord';
};

export type PutNotificationsExtensionsDiscordErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PutNotificationsExtensionsDiscordResponses = {
    /**
     * OK
     */
    200: ServicesNotificationsNotificationExtension;
};

export type PutNotificationsExtensionsDiscordResponse =
    PutNotificationsExtensionsDiscordResponses[keyof PutNotificationsExtensionsDiscordResponses];

export type PutNotificationsExtensionsGotifyData = {
    body: ServicesNotificationsPutExtensionRequestGotify;
    path?: never;
    query?: never;
    url: '/notifications/extensions/gotify';
};

export type PutNotificationsExtensionsGotifyErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PutNotificationsExtensionsGotifyResponses = {
    /**
     * OK
     */
    200: ServicesNotificationsNotificationExtension;
};

export type PutNotificationsExtensionsGotifyResponse =
    PutNotificationsExtensionsGotifyResponses[keyof PutNotificationsExtensionsGotifyResponses];

export type PutNotificationsExtensionsNtfyshData = {
    body: ServicesNotificationsPutExtensionRequestNtfySh;
    path?: never;
    query?: never;
    url: '/notifications/extensions/ntfysh';
};

export type PutNotificationsExtensionsNtfyshErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PutNotificationsExtensionsNtfyshResponses = {
    /**
     * OK
     */
    200: ServicesNotificationsNotificationExtension;
};

export type PutNotificationsExtensionsNtfyshResponse =
    PutNotificationsExtensionsNtfyshResponses[keyof PutNotificationsExtensionsNtfyshResponses];

export type PutNotificationsExtensionsTelegramData = {
    body: ServicesNotificationsPutExtensionRequestTelegram;
    path?: never;
    query?: never;
    url: '/notifications/extensions/telegram';
};

export type PutNotificationsExtensionsTelegramErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PutNotificationsExtensionsTelegramResponses = {
    /**
     * OK
     */
    200: ServicesNotificationsNotificationExtension;
};

export type PutNotificationsExtensionsTelegramResponse =
    PutNotificationsExtensionsTelegramResponses[keyof PutNotificationsExtensionsTelegramResponses];

export type DeleteNotificationsExtensionsByExtensionIdData = {
    body?: never;
    path: { extensionId: string };
    query?: never;
    url: '/notifications/extensions/{extensionId}';
};

export type DeleteNotificationsExtensionsByExtensionIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteNotificationsExtensionsByExtensionIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetLibrariesData = { body?: never; path?: never; query?: never; url: '/libraries' };

export type GetLibrariesResponses = {
    /**
     * OK
     */
    200: Array<ServicesLibrariesLibrary>;
};

export type GetLibrariesResponse = GetLibrariesResponses[keyof GetLibrariesResponses];

export type PutLibrariesKomgaData = { body: ServicesLibrariesAddKomgaLibraryRequest; path?: never; query?: never; url: '/libraries/komga' };

export type PutLibrariesKomgaErrors = {
    /**
     * Bad Request
     */
    400: string;
};

export type PutLibrariesKomgaError = PutLibrariesKomgaErrors[keyof PutLibrariesKomgaErrors];

export type PutLibrariesKomgaResponses = {
    /**
     * OK
     */
    200: string;
};

export type PutLibrariesKomgaResponse = PutLibrariesKomgaResponses[keyof PutLibrariesKomgaResponses];

export type PostLibrariesKomgaTestConnectionData = {
    body: ServicesLibrariesTestKomgaConnectionRequest;
    path?: never;
    query?: never;
    url: '/libraries/komga/test-connection';
};

export type PostLibrariesKomgaTestConnectionErrors = {
    /**
     * Bad Request
     */
    400: string;
};

export type PostLibrariesKomgaTestConnectionError = PostLibrariesKomgaTestConnectionErrors[keyof PostLibrariesKomgaTestConnectionErrors];

export type PostLibrariesKomgaTestConnectionResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteLibrariesByLibraryIdData = { body?: never; path: { libraryId: string }; query?: never; url: '/libraries/{libraryId}' };

export type DeleteLibrariesByLibraryIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteLibrariesByLibraryIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchLibrariesByLibraryIdData = {
    body: ServicesLibrariesPatchLibraryRequest;
    path: { libraryId: string };
    query?: never;
    url: '/libraries/{libraryId}';
};

export type PatchLibrariesByLibraryIdErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Not Found
     */
    404: unknown;
};

export type PatchLibrariesByLibraryIdError = PatchLibrariesByLibraryIdErrors[keyof PatchLibrariesByLibraryIdErrors];

export type PatchLibrariesByLibraryIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostLibrariesByLibraryIdLinkData = {
    body?: never;
    path: { libraryId: string };
    query?: never;
    url: '/libraries/{libraryId}/link';
};

export type PostLibrariesByLibraryIdLinkErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostLibrariesByLibraryIdLinkError = PostLibrariesByLibraryIdLinkErrors[keyof PostLibrariesByLibraryIdLinkErrors];

export type PostLibrariesByLibraryIdLinkResponses = {
    /**
     * OK
     */
    200: number | string;
};

export type PostLibrariesByLibraryIdLinkResponse = PostLibrariesByLibraryIdLinkResponses[keyof PostLibrariesByLibraryIdLinkResponses];

export type GetLibrariesMappingsByMangaIdData = {
    body?: never;
    path: { mangaId: string };
    query?: never;
    url: '/libraries/mappings/{mangaId}';
};

export type GetLibrariesMappingsByMangaIdResponses = {
    /**
     * OK
     */
    200: Array<ServicesLibrariesLibraryMangaLink>;
};

export type GetLibrariesMappingsByMangaIdResponse = GetLibrariesMappingsByMangaIdResponses[keyof GetLibrariesMappingsByMangaIdResponses];

export type GetAuthStatusData = { body?: never; path?: never; query?: never; url: '/auth/status' };

export type GetAuthStatusResponses = {
    /**
     * OK
     */
    200: ServicesAuthAuthStatusResponse;
};

export type GetAuthStatusResponse = GetAuthStatusResponses[keyof GetAuthStatusResponses];

export type PostAuthSetupData = { body: ServicesAuthSetupRequest; path?: never; query?: never; url: '/auth/setup' };

export type PostAuthSetupErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Conflict
     */
    409: unknown;
};

export type PostAuthSetupError = PostAuthSetupErrors[keyof PostAuthSetupErrors];

export type PostAuthSetupResponses = {
    /**
     * OK
     */
    200: ServicesAuthAuthTokenResponse;
};

export type PostAuthSetupResponse = PostAuthSetupResponses[keyof PostAuthSetupResponses];

export type PostAuthLoginData = { body: ServicesAuthSetupRequest; path?: never; query?: never; url: '/auth/login' };

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: ServicesAuthAuthTokenResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetAuthApikeysData = { body?: never; path?: never; query?: never; url: '/auth/apikeys' };

export type GetAuthApikeysResponses = {
    /**
     * OK
     */
    200: Array<ServicesAuthApiKeyResponse>;
};

export type GetAuthApikeysResponse = GetAuthApikeysResponses[keyof GetAuthApikeysResponses];

export type PostAuthApikeysData = { body: ServicesAuthCreateApiKeyRequest; path?: never; query?: never; url: '/auth/apikeys' };

export type PostAuthApikeysResponses = {
    /**
     * OK
     */
    200: ServicesAuthCreateApiKeyResponse;
};

export type PostAuthApikeysResponse = PostAuthApikeysResponses[keyof PostAuthApikeysResponses];

export type DeleteAuthApikeysByApiKeyIdData = { body?: never; path: { apiKeyId: string }; query?: never; url: '/auth/apikeys/{apiKeyId}' };

export type DeleteAuthApikeysByApiKeyIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteAuthApikeysByApiKeyIdResponses = {
    /**
     * OK
     */
    200: unknown;
};
