// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/mini';

export const zServicesMangaChapter = z.object({
    chapterId: z.uuid(),
    mangaId: z.uuid(),
    title: z.nullable(z.string().check(z.minLength(0), z.maxLength(2048))),
    volume: z.nullable(z.string().check(z.minLength(0), z.maxLength(16))),
    number: z.string().check(z.minLength(0), z.maxLength(16)),
    releaseDate: z.nullable(z.iso.datetime()),
});

export type ServicesMangaChapterZodType = z.infer<typeof zServicesMangaChapter>;

export const zServicesMangaContentRating = z.enum(['Safe', 'Suggestive', 'Erotica', 'Pornographic']);

export type ServicesMangaContentRatingZodType = z.infer<typeof zServicesMangaContentRating>;

export const zServicesMangaDownloadLink = z.object({
    downloadId: z.uuid(),
    downloadExtensionId: z.uuid(),
    identifier: z.string(),
    series: z.string().check(z.minLength(0), z.maxLength(1024)),
    summary: z.nullable(z.string().check(z.minLength(0), z.maxLength(4096))),
    language: z.nullish(z.string().check(z.minLength(0), z.maxLength(8))),
    url: z.nullable(z.string()),
    coverId: z.nullable(z.uuid()),
    nsfw: z.nullable(z.boolean()),
});

export type ServicesMangaDownloadLinkZodType = z.infer<typeof zServicesMangaDownloadLink>;

export const zServicesMangaIDownloadExtension = z.object({
    downloadExtensionsId: z.optional(z.uuid()),
    name: z.nullish(z.string()),
    iconUrl: z.nullish(z.string()),
});

export type ServicesMangaIDownloadExtensionZodType = z.infer<typeof zServicesMangaIDownloadExtension>;

export const zServicesMangaDownloadExtensionsList = z.object({ extensions: z.optional(z.array(zServicesMangaIDownloadExtension)) });

export type ServicesMangaDownloadExtensionsListZodType = z.infer<typeof zServicesMangaDownloadExtensionsList>;

export const zServicesMangaIMetadataExtension = z.object({
    metadataExtensionId: z.optional(z.uuid()),
    name: z.nullish(z.string()),
    iconUrl: z.nullish(z.string()),
});

export type ServicesMangaIMetadataExtensionZodType = z.infer<typeof zServicesMangaIMetadataExtension>;

export const zServicesMangaMangaDownloadLink = z.object({
    mangaId: z.uuid(),
    matched: z.boolean(),
    priority: z.union([
        z
            .int()
            .check(
                z.minimum(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }),
                z.maximum(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
            ),
        z.string().check(z.regex(/^-?(?:0|[1-9]\d*)$/)),
    ]),
    language: z.nullish(z.string().check(z.minLength(0), z.maxLength(8))),
    downloadId: z.uuid(),
    downloadExtensionId: z.uuid(),
    identifier: z.string(),
    series: z.string().check(z.minLength(0), z.maxLength(1024)),
    summary: z.nullable(z.string().check(z.minLength(0), z.maxLength(4096))),
    url: z.nullable(z.string()),
    coverId: z.nullable(z.uuid()),
    nsfw: z.nullable(z.boolean()),
});

export type ServicesMangaMangaDownloadLinkZodType = z.infer<typeof zServicesMangaMangaDownloadLink>;

export const zServicesMangaMetadataExtensionsList = z.object({ extensions: z.optional(z.array(zServicesMangaIMetadataExtension)) });

export type ServicesMangaMetadataExtensionsListZodType = z.infer<typeof zServicesMangaMetadataExtensionsList>;

export const zServicesMangaPatchMangaDownloadLinkRequest = z.object({
    matched: z.boolean(),
    priority: z.union([
        z
            .int()
            .check(
                z.minimum(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }),
                z.maximum(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
            ),
        z.string().check(z.regex(/^-?(?:0|[1-9]\d*)$/)),
    ]),
});

export type ServicesMangaPatchMangaDownloadLinkRequestZodType = z.infer<typeof zServicesMangaPatchMangaDownloadLinkRequest>;

export const zServicesMangaReleaseStatus = z.enum(['Ongoing', 'Complete', 'Hiatus', 'Cancelled']);

export type ServicesMangaReleaseStatusZodType = z.infer<typeof zServicesMangaReleaseStatus>;

export const zServicesMangaMetadata = z.object({
    metadataId: z.uuid(),
    metadataExtensionId: z.uuid(),
    identifier: z.string(),
    chosen: z.nullish(z.boolean()),
    series: z.string().check(z.minLength(0), z.maxLength(1024)),
    summary: z.nullable(z.string().check(z.minLength(0), z.maxLength(4096))),
    year: z.nullish(
        z.union([
            z
                .int()
                .check(
                    z.minimum(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }),
                    z.maximum(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
                ),
            z.string().check(z.regex(/^-?(?:0|[1-9]\d*)$/)),
        ])
    ),
    language: z.nullish(z.string().check(z.minLength(0), z.maxLength(8))),
    chaptersNumber: z.nullish(
        z.union([
            z
                .int()
                .check(
                    z.minimum(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }),
                    z.maximum(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
                ),
            z.string().check(z.regex(/^-?(?:0|[1-9]\d*)$/)),
        ])
    ),
    coverId: z.nullable(z.uuid()),
    genres: z.optional(z.array(z.string())),
    authors: z.optional(z.array(z.string())),
    artists: z.optional(z.array(z.string())),
    url: z.nullable(z.string()),
    status: z.nullish(zServicesMangaReleaseStatus),
    nsfw: z.nullable(z.boolean()),
});

export type ServicesMangaMetadataZodType = z.infer<typeof zServicesMangaMetadata>;

export const zServicesMangaManga = z.object({
    mangaId: z.uuid(),
    monitored: z.boolean(),
    metadataEntry: z.nullish(zServicesMangaMetadata),
    downloadLinks: z.nullish(z.array(zServicesMangaDownloadLink)),
});

export type ServicesMangaMangaZodType = z.infer<typeof zServicesMangaManga>;

export const zServicesMangaSearchQuery = z.object({
    title: z.nullish(z.string()),
    tags: z.nullish(z.array(z.string())),
    contentRating: z.nullish(zServicesMangaContentRating),
    year: z.nullish(
        z.union([
            z
                .int()
                .check(
                    z.minimum(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }),
                    z.maximum(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
                ),
            z.string().check(z.regex(/^-?(?:0|[1-9]\d*)$/)),
        ])
    ),
    author: z.nullish(z.string()),
    artist: z.nullish(z.string()),
    language: z.nullish(z.string()),
    mangaUpdatesSeriesId: z.nullish(
        z.union([
            z.coerce
                .bigint()
                .check(
                    z.minimum(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }),
                    z.maximum(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
                ),
            z.coerce
                .bigint()
                .check(
                    z.minimum(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }),
                    z.maximum(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
                ),
        ])
    ),
    mangaDexSeriesId: z.nullish(z.uuid()),
});

export type ServicesMangaSearchQueryZodType = z.infer<typeof zServicesMangaSearchQuery>;

export const zServicesMangaPostSearchMangaRequest = z.object({
    searchQuery: zServicesMangaSearchQuery,
    metadataExtensionIds: z.nullable(z.array(z.uuid())),
});

export type ServicesMangaPostSearchMangaRequestZodType = z.infer<typeof zServicesMangaPostSearchMangaRequest>;

export const zServicesTasksChapterSummary = z.object({
    chapterId: z.uuid(),
    mangaId: z.uuid(),
    title: z.nullish(z.string()),
    volume: z.nullish(z.string()),
    number: z.string(),
});

export type ServicesTasksChapterSummaryZodType = z.infer<typeof zServicesTasksChapterSummary>;

export const zServicesTasksMangaSummary = z.object({ mangaId: z.uuid(), series: z.nullish(z.string()) });

export type ServicesTasksMangaSummaryZodType = z.infer<typeof zServicesTasksMangaSummary>;

export const zServicesTasksTaskState = z.enum(['Pending', 'Blocked', 'Queued', 'Running', 'Completed', 'Failed']);

export type ServicesTasksTaskStateZodType = z.infer<typeof zServicesTasksTaskState>;

export const zServicesTasksTaskType = z.enum(['PeriodicTask', 'RunOnceTask']);

export type ServicesTasksTaskTypeZodType = z.infer<typeof zServicesTasksTaskType>;

export const zServicesTasksTaskChapterTask = z.object({
    kind: z.optional(z.enum(['chapterTask'])),
    chapter: zServicesTasksChapterSummary,
    manga: zServicesTasksMangaSummary,
    taskId: z.uuid(),
    taskTypeId: z.uuid(),
    taskTypeName: z.string(),
    taskType: zServicesTasksTaskType,
    lastRun: z.nullable(z.iso.datetime()),
    status: zServicesTasksTaskState,
    interval: z.nullish(z.string().check(z.regex(/^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$/))),
});

export type ServicesTasksTaskChapterTaskZodType = z.infer<typeof zServicesTasksTaskChapterTask>;

export const zServicesTasksTaskMangaTask = z.object({
    kind: z.optional(z.enum(['mangaTask'])),
    manga: zServicesTasksMangaSummary,
    taskId: z.uuid(),
    taskTypeId: z.uuid(),
    taskTypeName: z.string(),
    taskType: zServicesTasksTaskType,
    lastRun: z.nullable(z.iso.datetime()),
    status: zServicesTasksTaskState,
    interval: z.nullish(z.string().check(z.regex(/^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$/))),
});

export type ServicesTasksTaskMangaTaskZodType = z.infer<typeof zServicesTasksTaskMangaTask>;

export const zServicesTasksTaskTask = z.object({
    kind: z.optional(z.enum(['task'])),
    taskId: z.uuid(),
    taskTypeId: z.uuid(),
    taskTypeName: z.string(),
    taskType: zServicesTasksTaskType,
    lastRun: z.nullable(z.iso.datetime()),
    status: zServicesTasksTaskState,
    interval: z.nullish(z.string().check(z.regex(/^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$/))),
});

export type ServicesTasksTaskTaskZodType = z.infer<typeof zServicesTasksTaskTask>;

export const zServicesTasksTask = z.union([
    z.intersection(z.object({ kind: z.optional(z.literal('Services_Tasks_TaskTask')) }), zServicesTasksTaskTask),
    z.intersection(z.object({ kind: z.optional(z.literal('Services_Tasks_TaskMangaTask')) }), zServicesTasksTaskMangaTask),
    z.intersection(z.object({ kind: z.optional(z.literal('Services_Tasks_TaskChapterTask')) }), zServicesTasksTaskChapterTask),
]);

export type ServicesTasksTaskZodType = z.infer<typeof zServicesTasksTask>;

export const zServicesTasksWorkerStatus = z.enum(['Idle', 'Busy', 'Retiring']);

export type ServicesTasksWorkerStatusZodType = z.infer<typeof zServicesTasksWorkerStatus>;

export const zServicesTasksWorker = z.object({
    workerId: z.uuid(),
    status: zServicesTasksWorkerStatus,
    currentTaskId: z.nullish(z.uuid()),
    currentTaskTypeId: z.nullish(z.uuid()),
    startedAt: z.iso.datetime(),
    lastHeartbeat: z.iso.datetime(),
});

export type ServicesTasksWorkerZodType = z.infer<typeof zServicesTasksWorker>;

export const zServicesNotificationsNotificationExtensionType = z.enum(['Naprise', 'Discord', 'Gotify', 'NtfySh', 'Telegram']);

export type ServicesNotificationsNotificationExtensionTypeZodType = z.infer<typeof zServicesNotificationsNotificationExtensionType>;

export const zServicesNotificationsNotificationExtension = z.object({
    id: z.uuid(),
    name: z.string(),
    type: zServicesNotificationsNotificationExtensionType,
});

export type ServicesNotificationsNotificationExtensionZodType = z.infer<typeof zServicesNotificationsNotificationExtension>;

export const zServicesNotificationsPutExtensionRequest = z.object({ name: z.optional(z.string()) });

export type ServicesNotificationsPutExtensionRequestZodType = z.infer<typeof zServicesNotificationsPutExtensionRequest>;

export const zServicesNotificationsPutExtensionRequestDiscord = z.object({
    webhookId: z.string(),
    webhookToken: z.string(),
    name: z.string(),
});

export type ServicesNotificationsPutExtensionRequestDiscordZodType = z.infer<typeof zServicesNotificationsPutExtensionRequestDiscord>;

export const zServicesNotificationsPutExtensionRequestGotify = z.object({
    host: z.string(),
    port: z.union([
        z
            .int()
            .check(
                z.minimum(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }),
                z.maximum(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
            ),
        z.string().check(z.regex(/^-?(?:0|[1-9]\d*)$/)),
    ]),
    appToken: z.string(),
    name: z.string(),
});

export type ServicesNotificationsPutExtensionRequestGotifyZodType = z.infer<typeof zServicesNotificationsPutExtensionRequestGotify>;

export const zServicesNotificationsPutExtensionRequestNapriseServiceUrl = z.object({ serviceUrl: z.string(), name: z.string() });

export type ServicesNotificationsPutExtensionRequestNapriseServiceUrlZodType = z.infer<
    typeof zServicesNotificationsPutExtensionRequestNapriseServiceUrl
>;

export const zServicesNotificationsPutExtensionRequestNtfySh = z.object({
    host: z.string(),
    port: z.union([
        z
            .int()
            .check(
                z.minimum(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }),
                z.maximum(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
            ),
        z.string().check(z.regex(/^-?(?:0|[1-9]\d*)$/)),
    ]),
    topic: z.string(),
    user: z.nullish(z.string()),
    password: z.nullish(z.string()),
    name: z.string(),
});

export type ServicesNotificationsPutExtensionRequestNtfyShZodType = z.infer<typeof zServicesNotificationsPutExtensionRequestNtfySh>;

export const zServicesNotificationsPutExtensionRequestTelegram = z.object({ token: z.string(), chatId: z.string(), name: z.string() });

export type ServicesNotificationsPutExtensionRequestTelegramZodType = z.infer<typeof zServicesNotificationsPutExtensionRequestTelegram>;

export const zServicesLibrariesAddKomgaLibraryRequest = z.object({
    name: z.string(),
    baseUrl: z.string(),
    apiKey: z.nullish(z.string()),
    username: z.nullish(z.string()),
    password: z.nullish(z.string()),
    libraryRootPath: z.nullish(z.string()),
});

export type ServicesLibrariesAddKomgaLibraryRequestZodType = z.infer<typeof zServicesLibrariesAddKomgaLibraryRequest>;

export const zServicesLibrariesLibraryMangaLink = z.object({ libraryServiceId: z.uuid(), seriesUrl: z.string() });

export type ServicesLibrariesLibraryMangaLinkZodType = z.infer<typeof zServicesLibrariesLibraryMangaLink>;

export const zServicesLibrariesLibraryServiceType = z.enum(['Komga']);

export type ServicesLibrariesLibraryServiceTypeZodType = z.infer<typeof zServicesLibrariesLibraryServiceType>;

export const zServicesLibrariesLibrary = z.object({
    libraryServiceType: zServicesLibrariesLibraryServiceType,
    id: z.uuid(),
    baseUrl: z.string(),
});

export type ServicesLibrariesLibraryZodType = z.infer<typeof zServicesLibrariesLibrary>;

export const zServicesLibrariesPatchLibraryRequest = z.object({
    name: z.nullish(z.string()),
    apiKey: z.nullish(z.string()),
    username: z.nullish(z.string()),
    password: z.nullish(z.string()),
});

export type ServicesLibrariesPatchLibraryRequestZodType = z.infer<typeof zServicesLibrariesPatchLibraryRequest>;

export const zServicesLibrariesTestKomgaConnectionRequest = z.object({
    baseUrl: z.string(),
    apiKey: z.nullish(z.string()),
    username: z.nullish(z.string()),
    password: z.nullish(z.string()),
});

export type ServicesLibrariesTestKomgaConnectionRequestZodType = z.infer<typeof zServicesLibrariesTestKomgaConnectionRequest>;
