//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1234.0 using the following command:
// xscgen -n Common.Data https://raw.githubusercontent.com/anansi-project/comicinfo/refs/heads/main/schema/v2.0/ComicInfo.xsd
namespace Data
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ComicInfo", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ComicInfo", Namespace="")]
    public partial class ComicInfo
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _title = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Title")]
        public string Title
        {
            get
            {
                return _title;
            }
            set
            {
                _title = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _series = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Series")]
        public string Series
        {
            get
            {
                return _series;
            }
            set
            {
                _series = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _number = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Number")]
        public string Number
        {
            get
            {
                return _number;
            }
            set
            {
                _number = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _count = -1;
        
        [System.ComponentModel.DefaultValueAttribute(-1)]
        [System.Xml.Serialization.XmlElementAttribute("Count")]
        public int Count
        {
            get
            {
                return _count;
            }
            set
            {
                _count = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _volume = -1;
        
        [System.ComponentModel.DefaultValueAttribute(-1)]
        [System.Xml.Serialization.XmlElementAttribute("Volume")]
        public int Volume
        {
            get
            {
                return _volume;
            }
            set
            {
                _volume = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _alternateSeries = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("AlternateSeries")]
        public string AlternateSeries
        {
            get
            {
                return _alternateSeries;
            }
            set
            {
                _alternateSeries = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _alternateNumber = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("AlternateNumber")]
        public string AlternateNumber
        {
            get
            {
                return _alternateNumber;
            }
            set
            {
                _alternateNumber = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _alternateCount = -1;
        
        [System.ComponentModel.DefaultValueAttribute(-1)]
        [System.Xml.Serialization.XmlElementAttribute("AlternateCount")]
        public int AlternateCount
        {
            get
            {
                return _alternateCount;
            }
            set
            {
                _alternateCount = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _summary = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Summary")]
        public string Summary
        {
            get
            {
                return _summary;
            }
            set
            {
                _summary = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _notes = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Notes")]
        public string Notes
        {
            get
            {
                return _notes;
            }
            set
            {
                _notes = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _year = -1;
        
        [System.ComponentModel.DefaultValueAttribute(-1)]
        [System.Xml.Serialization.XmlElementAttribute("Year")]
        public int Year
        {
            get
            {
                return _year;
            }
            set
            {
                _year = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _month = -1;
        
        [System.ComponentModel.DefaultValueAttribute(-1)]
        [System.Xml.Serialization.XmlElementAttribute("Month")]
        public int Month
        {
            get
            {
                return _month;
            }
            set
            {
                _month = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _day = -1;
        
        [System.ComponentModel.DefaultValueAttribute(-1)]
        [System.Xml.Serialization.XmlElementAttribute("Day")]
        public int Day
        {
            get
            {
                return _day;
            }
            set
            {
                _day = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _writer = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Writer")]
        public string Writer
        {
            get
            {
                return _writer;
            }
            set
            {
                _writer = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _penciller = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Penciller")]
        public string Penciller
        {
            get
            {
                return _penciller;
            }
            set
            {
                _penciller = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _inker = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Inker")]
        public string Inker
        {
            get
            {
                return _inker;
            }
            set
            {
                _inker = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _colorist = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Colorist")]
        public string Colorist
        {
            get
            {
                return _colorist;
            }
            set
            {
                _colorist = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _letterer = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Letterer")]
        public string Letterer
        {
            get
            {
                return _letterer;
            }
            set
            {
                _letterer = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _coverArtist = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("CoverArtist")]
        public string CoverArtist
        {
            get
            {
                return _coverArtist;
            }
            set
            {
                _coverArtist = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _editor = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Editor")]
        public string Editor
        {
            get
            {
                return _editor;
            }
            set
            {
                _editor = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _publisher = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Publisher")]
        public string Publisher
        {
            get
            {
                return _publisher;
            }
            set
            {
                _publisher = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _imprint = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Imprint")]
        public string Imprint
        {
            get
            {
                return _imprint;
            }
            set
            {
                _imprint = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _genre = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Genre")]
        public string Genre
        {
            get
            {
                return _genre;
            }
            set
            {
                _genre = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _web = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Web")]
        public string Web
        {
            get
            {
                return _web;
            }
            set
            {
                _web = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _pageCount = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlElementAttribute("PageCount")]
        public int PageCount
        {
            get
            {
                return _pageCount;
            }
            set
            {
                _pageCount = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _languageIso = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("LanguageISO")]
        public string LanguageIso
        {
            get
            {
                return _languageIso;
            }
            set
            {
                _languageIso = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _format = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Format")]
        public string Format
        {
            get
            {
                return _format;
            }
            set
            {
                _format = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private YesNo _blackAndWhite = Data.YesNo.Unknown;
        
        [System.ComponentModel.DefaultValueAttribute(Data.YesNo.Unknown)]
        [System.Xml.Serialization.XmlElementAttribute("BlackAndWhite")]
        public YesNo BlackAndWhite
        {
            get
            {
                return _blackAndWhite;
            }
            set
            {
                _blackAndWhite = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Manga _manga = Data.Manga.Unknown;
        
        [System.ComponentModel.DefaultValueAttribute(Data.Manga.Unknown)]
        [System.Xml.Serialization.XmlElementAttribute("Manga")]
        public Manga Manga
        {
            get
            {
                return _manga;
            }
            set
            {
                _manga = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _characters = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Characters")]
        public string Characters
        {
            get
            {
                return _characters;
            }
            set
            {
                _characters = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _teams = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Teams")]
        public string Teams
        {
            get
            {
                return _teams;
            }
            set
            {
                _teams = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _locations = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Locations")]
        public string Locations
        {
            get
            {
                return _locations;
            }
            set
            {
                _locations = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _scanInformation = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("ScanInformation")]
        public string ScanInformation
        {
            get
            {
                return _scanInformation;
            }
            set
            {
                _scanInformation = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _storyArc = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("StoryArc")]
        public string StoryArc
        {
            get
            {
                return _storyArc;
            }
            set
            {
                _storyArc = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _seriesGroup = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("SeriesGroup")]
        public string SeriesGroup
        {
            get
            {
                return _seriesGroup;
            }
            set
            {
                _seriesGroup = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private AgeRating _ageRating = Data.AgeRating.Unknown;
        
        [System.ComponentModel.DefaultValueAttribute(Data.AgeRating.Unknown)]
        [System.Xml.Serialization.XmlElementAttribute("AgeRating")]
        public AgeRating AgeRating
        {
            get
            {
                return _ageRating;
            }
            set
            {
                _ageRating = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ComicPageInfo> _pages;
        
        [System.Xml.Serialization.XmlArrayAttribute("Pages")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Page", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<ComicPageInfo> Pages
        {
            get
            {
                return _pages;
            }
            private set
            {
                _pages = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Pages collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PagesSpecified
        {
            get
            {
                return (this.Pages.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ComicInfo" /> class.</para>
        /// </summary>
        public ComicInfo()
        {
            this._pages = new System.Collections.ObjectModel.Collection<ComicPageInfo>();
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Maximum inclusive value: 5.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "0", "5")]
        [System.Xml.Serialization.XmlElementAttribute("CommunityRating")]
        public decimal CommunityRating { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CommunityRating property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommunityRatingSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _mainCharacterOrTeam = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("MainCharacterOrTeam")]
        public string MainCharacterOrTeam
        {
            get
            {
                return _mainCharacterOrTeam;
            }
            set
            {
                _mainCharacterOrTeam = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _review = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlElementAttribute("Review")]
        public string Review
        {
            get
            {
                return _review;
            }
            set
            {
                _review = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("YesNo", Namespace="")]
    public enum YesNo
    {
        
        Unknown,
        
        No,
        
        Yes,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Manga", Namespace="")]
    public enum Manga
    {
        
        Unknown,
        
        No,
        
        Yes,
        
        YesAndRightToLeft,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AgeRating", Namespace="")]
    public enum AgeRating
    {
        
        Unknown,
        
        [System.Xml.Serialization.XmlEnumAttribute("Adults Only 18+")]
        AdultsOnly18,
        
        [System.Xml.Serialization.XmlEnumAttribute("Early Childhood")]
        EarlyChildhood,
        
        Everyone,
        
        [System.Xml.Serialization.XmlEnumAttribute("Everyone 10+")]
        Everyone10,
        
        G,
        
        [System.Xml.Serialization.XmlEnumAttribute("Kids to Adults")]
        KidsToAdults,
        
        M,
        
        [System.Xml.Serialization.XmlEnumAttribute("MA15+")]
        Ma15,
        
        [System.Xml.Serialization.XmlEnumAttribute("Mature 17+")]
        Mature17,
        
        [System.Xml.Serialization.XmlEnumAttribute("PG")]
        Pg,
        
        [System.Xml.Serialization.XmlEnumAttribute("R18+")]
        R18,
        
        [System.Xml.Serialization.XmlEnumAttribute("Rating Pending")]
        RatingPending,
        
        Teen,
        
        [System.Xml.Serialization.XmlEnumAttribute("X18+")]
        X18,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ArrayOfComicPageInfo", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ArrayOfComicPageInfo
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ComicPageInfo> _page;
        
        [System.Xml.Serialization.XmlElementAttribute("Page", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<ComicPageInfo> Page
        {
            get
            {
                return _page;
            }
            private set
            {
                _page = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Page collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PageSpecified
        {
            get
            {
                return (this.Page.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ArrayOfComicPageInfo" /> class.</para>
        /// </summary>
        public ArrayOfComicPageInfo()
        {
            this._page = new System.Collections.ObjectModel.Collection<ComicPageInfo>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1234.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ComicPageInfo", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComicPageInfo
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Image")]
        public int Image { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _type;
        
        [System.Xml.Serialization.XmlAttributeAttribute("Type")]
        public System.Collections.ObjectModel.Collection<string> Type
        {
            get
            {
                return _type;
            }
            private set
            {
                _type = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Type collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified
        {
            get
            {
                return (this.Type.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ComicPageInfo" /> class.</para>
        /// </summary>
        public ComicPageInfo()
        {
            this._type = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _doublePage = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("DoublePage")]
        public bool DoublePage
        {
            get
            {
                return _doublePage;
            }
            set
            {
                _doublePage = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private long _imageSize = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("ImageSize")]
        public long ImageSize
        {
            get
            {
                return _imageSize;
            }
            set
            {
                _imageSize = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _key = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlAttributeAttribute("Key")]
        public string Key
        {
            get
            {
                return _key;
            }
            set
            {
                _key = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _bookmark = "";
        
        [System.ComponentModel.DefaultValueAttribute("")]
        [System.Xml.Serialization.XmlAttributeAttribute("Bookmark")]
        public string Bookmark
        {
            get
            {
                return _bookmark;
            }
            set
            {
                _bookmark = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _imageWidth = -1;
        
        [System.ComponentModel.DefaultValueAttribute(-1)]
        [System.Xml.Serialization.XmlAttributeAttribute("ImageWidth")]
        public int ImageWidth
        {
            get
            {
                return _imageWidth;
            }
            set
            {
                _imageWidth = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _imageHeight = -1;
        
        [System.ComponentModel.DefaultValueAttribute(-1)]
        [System.Xml.Serialization.XmlAttributeAttribute("ImageHeight")]
        public int ImageHeight
        {
            get
            {
                return _imageHeight;
            }
            set
            {
                _imageHeight = value;
            }
        }
    }
}
