/*
 * Komga API
 *
 * Komga REST API.  ## Reference  Check the API reference: - on the [Komga website](https://komga.org/docs/openapi/komga-api) - on any running Komga instance at `/swagger-ui.html` - on [GitHub](https://raw.githubusercontent.com/gotson/komga/refs/heads/master/komga/docs/openapi.json)  ## Authentication  Most endpoints require authentication. Authentication is done using either: - Basic Authentication - Passing an API Key in the `X-API-Key` header  ## Sessions  Upon successful authentication, a session is created, and can be reused.  - By default, a `KOMGA-SESSION` cookie is set via `Set-Cookie` response header. This works well for browsers and clients that can handle cookies. - If you specify a header `X-Auth-Token` during authentication, the session ID will be returned via this same header. You can then pass that header again for subsequent requests to reuse the session.  If you need to set the session cookie later on, you can call `/api/v1/login/set-cookie` with `X-Auth-Token`. The response will contain the `Set-Cookie` header.  ## Remember Me  During authentication, if a request parameter `remember-me` is passed and set to `true`, the server will also return a `komga-remember-me` cookie. This cookie will be used to login automatically even if the session has expired.  ## Logout  You can explicitly logout an existing session by calling `/api/logout`. This would return a `204`.  ## Deprecation  API endpoints marked as deprecated will be removed in the next major version.
 *
 * The version of the OpenAPI document: 1.24.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Komga.Client.Client;
using Komga.Client.Model;

namespace Komga.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IClientSettingsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Delete global settings
        /// </summary>
        /// <remarks>
        /// Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;  Required role: **ADMIN**
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns></returns>
        void DeleteGlobalSettings(List<string> requestBody);

        /// <summary>
        /// Delete global settings
        /// </summary>
        /// <remarks>
        /// Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;  Required role: **ADMIN**
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteGlobalSettingsWithHttpInfo(List<string> requestBody);
        /// <summary>
        /// Delete user settings
        /// </summary>
        /// <remarks>
        /// Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns></returns>
        void DeleteUserSettings(List<string> requestBody);

        /// <summary>
        /// Delete user settings
        /// </summary>
        /// <remarks>
        /// Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteUserSettingsWithHttpInfo(List<string> requestBody);
        /// <summary>
        /// Retrieve global client settings
        /// </summary>
        /// <remarks>
        /// For unauthenticated users, only settings with &#39;allowUnauthorized&#x3D;true&#39; will be returned.
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Dictionary&lt;string, ClientSettingDto&gt;</returns>
        Dictionary<string, ClientSettingDto> GetGlobalSettings();

        /// <summary>
        /// Retrieve global client settings
        /// </summary>
        /// <remarks>
        /// For unauthenticated users, only settings with &#39;allowUnauthorized&#x3D;true&#39; will be returned.
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Dictionary&lt;string, ClientSettingDto&gt;</returns>
        ApiResponse<Dictionary<string, ClientSettingDto>> GetGlobalSettingsWithHttpInfo();
        /// <summary>
        /// Retrieve user client settings
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Dictionary&lt;string, ClientSettingDto&gt;</returns>
        Dictionary<string, ClientSettingDto> GetUserSettings();

        /// <summary>
        /// Retrieve user client settings
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Dictionary&lt;string, ClientSettingDto&gt;</returns>
        ApiResponse<Dictionary<string, ClientSettingDto>> GetUserSettingsWithHttpInfo();
        /// <summary>
        /// Save global settings
        /// </summary>
        /// <remarks>
        /// Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;  Required role: **ADMIN**
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns></returns>
        void SaveGlobalSetting(Dictionary<string, ClientSettingGlobalUpdateDto> requestBody);

        /// <summary>
        /// Save global settings
        /// </summary>
        /// <remarks>
        /// Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;  Required role: **ADMIN**
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> SaveGlobalSettingWithHttpInfo(Dictionary<string, ClientSettingGlobalUpdateDto> requestBody);
        /// <summary>
        /// Save user settings
        /// </summary>
        /// <remarks>
        /// Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns></returns>
        void SaveUserSetting(Dictionary<string, ClientSettingUserUpdateDto> requestBody);

        /// <summary>
        /// Save user settings
        /// </summary>
        /// <remarks>
        /// Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> SaveUserSettingWithHttpInfo(Dictionary<string, ClientSettingUserUpdateDto> requestBody);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IClientSettingsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Delete global settings
        /// </summary>
        /// <remarks>
        /// Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;  Required role: **ADMIN**
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteGlobalSettingsAsync(List<string> requestBody, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete global settings
        /// </summary>
        /// <remarks>
        /// Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;  Required role: **ADMIN**
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteGlobalSettingsWithHttpInfoAsync(List<string> requestBody, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Delete user settings
        /// </summary>
        /// <remarks>
        /// Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteUserSettingsAsync(List<string> requestBody, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete user settings
        /// </summary>
        /// <remarks>
        /// Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteUserSettingsWithHttpInfoAsync(List<string> requestBody, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Retrieve global client settings
        /// </summary>
        /// <remarks>
        /// For unauthenticated users, only settings with &#39;allowUnauthorized&#x3D;true&#39; will be returned.
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, ClientSettingDto&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, ClientSettingDto>> GetGlobalSettingsAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieve global client settings
        /// </summary>
        /// <remarks>
        /// For unauthenticated users, only settings with &#39;allowUnauthorized&#x3D;true&#39; will be returned.
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, ClientSettingDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, ClientSettingDto>>> GetGlobalSettingsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Retrieve user client settings
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, ClientSettingDto&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, ClientSettingDto>> GetUserSettingsAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieve user client settings
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, ClientSettingDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, ClientSettingDto>>> GetUserSettingsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Save global settings
        /// </summary>
        /// <remarks>
        /// Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;  Required role: **ADMIN**
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task SaveGlobalSettingAsync(Dictionary<string, ClientSettingGlobalUpdateDto> requestBody, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Save global settings
        /// </summary>
        /// <remarks>
        /// Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;  Required role: **ADMIN**
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> SaveGlobalSettingWithHttpInfoAsync(Dictionary<string, ClientSettingGlobalUpdateDto> requestBody, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Save user settings
        /// </summary>
        /// <remarks>
        /// Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task SaveUserSettingAsync(Dictionary<string, ClientSettingUserUpdateDto> requestBody, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Save user settings
        /// </summary>
        /// <remarks>
        /// Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;
        /// </remarks>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> SaveUserSettingWithHttpInfoAsync(Dictionary<string, ClientSettingUserUpdateDto> requestBody, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IClientSettingsApi : IClientSettingsApiSync, IClientSettingsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ClientSettingsApi : IDisposable, IClientSettingsApi
    {
        private Komga.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ClientSettingsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public ClientSettingsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClientSettingsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public ClientSettingsApi(string basePath)
        {
            this.Configuration = Komga.Client.Client.Configuration.MergeConfigurations(
                Komga.Client.Client.GlobalConfiguration.Instance,
                new Komga.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Komga.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Komga.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClientSettingsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public ClientSettingsApi(Komga.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Komga.Client.Client.Configuration.MergeConfigurations(
                Komga.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Komga.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Komga.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClientSettingsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ClientSettingsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClientSettingsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ClientSettingsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Komga.Client.Client.Configuration.MergeConfigurations(
                Komga.Client.Client.GlobalConfiguration.Instance,
                new Komga.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Komga.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Komga.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClientSettingsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ClientSettingsApi(HttpClient client, Komga.Client.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Komga.Client.Client.Configuration.MergeConfigurations(
                Komga.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Komga.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Komga.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClientSettingsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ClientSettingsApi(Komga.Client.Client.ISynchronousClient client, Komga.Client.Client.IAsynchronousClient asyncClient, Komga.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Komga.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Komga.Client.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Komga.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Komga.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Komga.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Komga.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Delete global settings Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;  Required role: **ADMIN**
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns></returns>
        public void DeleteGlobalSettings(List<string> requestBody)
        {
            DeleteGlobalSettingsWithHttpInfo(requestBody);
        }

        /// <summary>
        /// Delete global settings Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;  Required role: **ADMIN**
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Komga.Client.Client.ApiResponse<Object> DeleteGlobalSettingsWithHttpInfo(List<string> requestBody)
        {
            // verify the required parameter 'requestBody' is set
            if (requestBody == null)
                throw new Komga.Client.Client.ApiException(400, "Missing required parameter 'requestBody' when calling ClientSettingsApi->DeleteGlobalSettings");

            Komga.Client.Client.RequestOptions localVarRequestOptions = new Komga.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = Komga.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Komga.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = requestBody;

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Komga.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/api/v1/client-settings/global", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteGlobalSettings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete global settings Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;  Required role: **ADMIN**
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteGlobalSettingsAsync(List<string> requestBody, System.Threading.CancellationToken cancellationToken = default)
        {
            await DeleteGlobalSettingsWithHttpInfoAsync(requestBody, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Delete global settings Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;  Required role: **ADMIN**
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Komga.Client.Client.ApiResponse<Object>> DeleteGlobalSettingsWithHttpInfoAsync(List<string> requestBody, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'requestBody' is set
            if (requestBody == null)
                throw new Komga.Client.Client.ApiException(400, "Missing required parameter 'requestBody' when calling ClientSettingsApi->DeleteGlobalSettings");


            Komga.Client.Client.RequestOptions localVarRequestOptions = new Komga.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };


            var localVarContentType = Komga.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Komga.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = requestBody;

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Komga.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/api/v1/client-settings/global", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteGlobalSettings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete user settings Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns></returns>
        public void DeleteUserSettings(List<string> requestBody)
        {
            DeleteUserSettingsWithHttpInfo(requestBody);
        }

        /// <summary>
        /// Delete user settings Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Komga.Client.Client.ApiResponse<Object> DeleteUserSettingsWithHttpInfo(List<string> requestBody)
        {
            // verify the required parameter 'requestBody' is set
            if (requestBody == null)
                throw new Komga.Client.Client.ApiException(400, "Missing required parameter 'requestBody' when calling ClientSettingsApi->DeleteUserSettings");

            Komga.Client.Client.RequestOptions localVarRequestOptions = new Komga.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = Komga.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Komga.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = requestBody;

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Komga.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/api/v1/client-settings/user", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteUserSettings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete user settings Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteUserSettingsAsync(List<string> requestBody, System.Threading.CancellationToken cancellationToken = default)
        {
            await DeleteUserSettingsWithHttpInfoAsync(requestBody, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Delete user settings Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Komga.Client.Client.ApiResponse<Object>> DeleteUserSettingsWithHttpInfoAsync(List<string> requestBody, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'requestBody' is set
            if (requestBody == null)
                throw new Komga.Client.Client.ApiException(400, "Missing required parameter 'requestBody' when calling ClientSettingsApi->DeleteUserSettings");


            Komga.Client.Client.RequestOptions localVarRequestOptions = new Komga.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };


            var localVarContentType = Komga.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Komga.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = requestBody;

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Komga.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/api/v1/client-settings/user", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteUserSettings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve global client settings For unauthenticated users, only settings with &#39;allowUnauthorized&#x3D;true&#39; will be returned.
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Dictionary&lt;string, ClientSettingDto&gt;</returns>
        public Dictionary<string, ClientSettingDto> GetGlobalSettings()
        {
            Komga.Client.Client.ApiResponse<Dictionary<string, ClientSettingDto>> localVarResponse = GetGlobalSettingsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve global client settings For unauthenticated users, only settings with &#39;allowUnauthorized&#x3D;true&#39; will be returned.
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Dictionary&lt;string, ClientSettingDto&gt;</returns>
        public Komga.Client.Client.ApiResponse<Dictionary<string, ClientSettingDto>> GetGlobalSettingsWithHttpInfo()
        {
            Komga.Client.Client.RequestOptions localVarRequestOptions = new Komga.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };

            var localVarContentType = Komga.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Komga.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<Dictionary<string, ClientSettingDto>>("/api/v1/client-settings/global/list", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetGlobalSettings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve global client settings For unauthenticated users, only settings with &#39;allowUnauthorized&#x3D;true&#39; will be returned.
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, ClientSettingDto&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, ClientSettingDto>> GetGlobalSettingsAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            Komga.Client.Client.ApiResponse<Dictionary<string, ClientSettingDto>> localVarResponse = await GetGlobalSettingsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve global client settings For unauthenticated users, only settings with &#39;allowUnauthorized&#x3D;true&#39; will be returned.
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, ClientSettingDto&gt;)</returns>
        public async System.Threading.Tasks.Task<Komga.Client.Client.ApiResponse<Dictionary<string, ClientSettingDto>>> GetGlobalSettingsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            Komga.Client.Client.RequestOptions localVarRequestOptions = new Komga.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };


            var localVarContentType = Komga.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Komga.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Dictionary<string, ClientSettingDto>>("/api/v1/client-settings/global/list", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetGlobalSettings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve user client settings 
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Dictionary&lt;string, ClientSettingDto&gt;</returns>
        public Dictionary<string, ClientSettingDto> GetUserSettings()
        {
            Komga.Client.Client.ApiResponse<Dictionary<string, ClientSettingDto>> localVarResponse = GetUserSettingsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve user client settings 
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Dictionary&lt;string, ClientSettingDto&gt;</returns>
        public Komga.Client.Client.ApiResponse<Dictionary<string, ClientSettingDto>> GetUserSettingsWithHttpInfo()
        {
            Komga.Client.Client.RequestOptions localVarRequestOptions = new Komga.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };

            var localVarContentType = Komga.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Komga.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Komga.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Dictionary<string, ClientSettingDto>>("/api/v1/client-settings/user/list", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUserSettings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve user client settings 
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, ClientSettingDto&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, ClientSettingDto>> GetUserSettingsAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            Komga.Client.Client.ApiResponse<Dictionary<string, ClientSettingDto>> localVarResponse = await GetUserSettingsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve user client settings 
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, ClientSettingDto&gt;)</returns>
        public async System.Threading.Tasks.Task<Komga.Client.Client.ApiResponse<Dictionary<string, ClientSettingDto>>> GetUserSettingsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            Komga.Client.Client.RequestOptions localVarRequestOptions = new Komga.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };


            var localVarContentType = Komga.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Komga.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Komga.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Dictionary<string, ClientSettingDto>>("/api/v1/client-settings/user/list", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUserSettings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Save global settings Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;  Required role: **ADMIN**
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns></returns>
        public void SaveGlobalSetting(Dictionary<string, ClientSettingGlobalUpdateDto> requestBody)
        {
            SaveGlobalSettingWithHttpInfo(requestBody);
        }

        /// <summary>
        /// Save global settings Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;  Required role: **ADMIN**
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Komga.Client.Client.ApiResponse<Object> SaveGlobalSettingWithHttpInfo(Dictionary<string, ClientSettingGlobalUpdateDto> requestBody)
        {
            // verify the required parameter 'requestBody' is set
            if (requestBody == null)
                throw new Komga.Client.Client.ApiException(400, "Missing required parameter 'requestBody' when calling ClientSettingsApi->SaveGlobalSetting");

            Komga.Client.Client.RequestOptions localVarRequestOptions = new Komga.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = Komga.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Komga.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = requestBody;

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Komga.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<Object>("/api/v1/client-settings/global", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SaveGlobalSetting", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Save global settings Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;  Required role: **ADMIN**
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task SaveGlobalSettingAsync(Dictionary<string, ClientSettingGlobalUpdateDto> requestBody, System.Threading.CancellationToken cancellationToken = default)
        {
            await SaveGlobalSettingWithHttpInfoAsync(requestBody, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Save global settings Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;  Required role: **ADMIN**
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Komga.Client.Client.ApiResponse<Object>> SaveGlobalSettingWithHttpInfoAsync(Dictionary<string, ClientSettingGlobalUpdateDto> requestBody, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'requestBody' is set
            if (requestBody == null)
                throw new Komga.Client.Client.ApiException(400, "Missing required parameter 'requestBody' when calling ClientSettingsApi->SaveGlobalSetting");


            Komga.Client.Client.RequestOptions localVarRequestOptions = new Komga.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };


            var localVarContentType = Komga.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Komga.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = requestBody;

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Komga.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PatchAsync<Object>("/api/v1/client-settings/global", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SaveGlobalSetting", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Save user settings Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns></returns>
        public void SaveUserSetting(Dictionary<string, ClientSettingUserUpdateDto> requestBody)
        {
            SaveUserSettingWithHttpInfo(requestBody);
        }

        /// <summary>
        /// Save user settings Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Komga.Client.Client.ApiResponse<Object> SaveUserSettingWithHttpInfo(Dictionary<string, ClientSettingUserUpdateDto> requestBody)
        {
            // verify the required parameter 'requestBody' is set
            if (requestBody == null)
                throw new Komga.Client.Client.ApiException(400, "Missing required parameter 'requestBody' when calling ClientSettingsApi->SaveUserSetting");

            Komga.Client.Client.RequestOptions localVarRequestOptions = new Komga.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = Komga.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Komga.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = requestBody;

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Komga.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<Object>("/api/v1/client-settings/user", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SaveUserSetting", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Save user settings Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task SaveUserSettingAsync(Dictionary<string, ClientSettingUserUpdateDto> requestBody, System.Threading.CancellationToken cancellationToken = default)
        {
            await SaveUserSettingWithHttpInfoAsync(requestBody, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Save user settings Setting key should be a valid lowercase namespace string like &#39;application.domain.key&#39;
        /// </summary>
        /// <exception cref="Komga.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Komga.Client.Client.ApiResponse<Object>> SaveUserSettingWithHttpInfoAsync(Dictionary<string, ClientSettingUserUpdateDto> requestBody, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'requestBody' is set
            if (requestBody == null)
                throw new Komga.Client.Client.ApiException(400, "Missing required parameter 'requestBody' when calling ClientSettingsApi->SaveUserSetting");


            Komga.Client.Client.RequestOptions localVarRequestOptions = new Komga.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };


            var localVarContentType = Komga.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Komga.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = requestBody;

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }
            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Komga.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PatchAsync<Object>("/api/v1/client-settings/user", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SaveUserSetting", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
