/*
 * Komga API
 *
 * Komga REST API.  ## Reference  Check the API reference: - on the [Komga website](https://komga.org/docs/openapi/komga-api) - on any running Komga instance at `/swagger-ui.html` - on [GitHub](https://raw.githubusercontent.com/gotson/komga/refs/heads/master/komga/docs/openapi.json)  ## Authentication  Most endpoints require authentication. Authentication is done using either: - Basic Authentication - Passing an API Key in the `X-API-Key` header  ## Sessions  Upon successful authentication, a session is created, and can be reused.  - By default, a `KOMGA-SESSION` cookie is set via `Set-Cookie` response header. This works well for browsers and clients that can handle cookies. - If you specify a header `X-Auth-Token` during authentication, the session ID will be returned via this same header. You can then pass that header again for subsequent requests to reuse the session.  If you need to set the session cookie later on, you can call `/api/v1/login/set-cookie` with `X-Auth-Token`. The response will contain the `Set-Cookie` header.  ## Remember Me  During authentication, if a request parameter `remember-me` is passed and set to `true`, the server will also return a `komga-remember-me` cookie. This cookie will be used to login automatically even if the session has expired.  ## Logout  You can explicitly logout an existing session by calling `/api/logout`. This would return a `204`.  ## Deprecation  API endpoints marked as deprecated will be removed in the next major version.
 *
 * The version of the OpenAPI document: 1.24.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Komga.Client.Client.FileParameter;
using OpenAPIDateConverter = Komga.Client.Client.OpenAPIDateConverter;

namespace Komga.Client.Model
{
    /// <summary>
    /// BookMetadataAggregationDto
    /// </summary>
    [DataContract(Name = "BookMetadataAggregationDto")]
    public partial class BookMetadataAggregationDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BookMetadataAggregationDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BookMetadataAggregationDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BookMetadataAggregationDto" /> class.
        /// </summary>
        /// <param name="authors">authors (required).</param>
        /// <param name="created">created (required).</param>
        /// <param name="lastModified">lastModified (required).</param>
        /// <param name="releaseDate">releaseDate.</param>
        /// <param name="summary">summary (required).</param>
        /// <param name="summaryNumber">summaryNumber (required).</param>
        /// <param name="tags">tags (required).</param>
        public BookMetadataAggregationDto(List<AuthorDto> authors = default, DateTime created = default, DateTime lastModified = default, DateOnly releaseDate = default, string summary = default, string summaryNumber = default, List<string> tags = default)
        {
            // to ensure "authors" is required (not null)
            if (authors == null)
            {
                throw new ArgumentNullException("authors is a required property for BookMetadataAggregationDto and cannot be null");
            }
            this.Authors = authors;
            this.Created = created;
            this.LastModified = lastModified;
            // to ensure "summary" is required (not null)
            if (summary == null)
            {
                throw new ArgumentNullException("summary is a required property for BookMetadataAggregationDto and cannot be null");
            }
            this.Summary = summary;
            // to ensure "summaryNumber" is required (not null)
            if (summaryNumber == null)
            {
                throw new ArgumentNullException("summaryNumber is a required property for BookMetadataAggregationDto and cannot be null");
            }
            this.SummaryNumber = summaryNumber;
            // to ensure "tags" is required (not null)
            if (tags == null)
            {
                throw new ArgumentNullException("tags is a required property for BookMetadataAggregationDto and cannot be null");
            }
            this.Tags = tags;
            this.ReleaseDate = releaseDate;
        }

        /// <summary>
        /// Gets or Sets Authors
        /// </summary>
        [DataMember(Name = "authors", IsRequired = true, EmitDefaultValue = true)]
        public List<AuthorDto> Authors { get; set; }

        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [DataMember(Name = "created", IsRequired = true, EmitDefaultValue = true)]
        public DateTime Created { get; set; }

        /// <summary>
        /// Gets or Sets LastModified
        /// </summary>
        [DataMember(Name = "lastModified", IsRequired = true, EmitDefaultValue = true)]
        public DateTime LastModified { get; set; }

        /// <summary>
        /// Gets or Sets ReleaseDate
        /// </summary>
        [DataMember(Name = "releaseDate", EmitDefaultValue = false)]
        public DateOnly ReleaseDate { get; set; }

        /// <summary>
        /// Gets or Sets Summary
        /// </summary>
        [DataMember(Name = "summary", IsRequired = true, EmitDefaultValue = true)]
        public string Summary { get; set; }

        /// <summary>
        /// Gets or Sets SummaryNumber
        /// </summary>
        [DataMember(Name = "summaryNumber", IsRequired = true, EmitDefaultValue = true)]
        public string SummaryNumber { get; set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [DataMember(Name = "tags", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BookMetadataAggregationDto {\n");
            sb.Append("  Authors: ").Append(Authors).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  LastModified: ").Append(LastModified).Append("\n");
            sb.Append("  ReleaseDate: ").Append(ReleaseDate).Append("\n");
            sb.Append("  Summary: ").Append(Summary).Append("\n");
            sb.Append("  SummaryNumber: ").Append(SummaryNumber).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
