/*
 * Komga API
 *
 * Komga REST API.  ## Reference  Check the API reference: - on the [Komga website](https://komga.org/docs/openapi/komga-api) - on any running Komga instance at `/swagger-ui.html` - on [GitHub](https://raw.githubusercontent.com/gotson/komga/refs/heads/master/komga/docs/openapi.json)  ## Authentication  Most endpoints require authentication. Authentication is done using either: - Basic Authentication - Passing an API Key in the `X-API-Key` header  ## Sessions  Upon successful authentication, a session is created, and can be reused.  - By default, a `KOMGA-SESSION` cookie is set via `Set-Cookie` response header. This works well for browsers and clients that can handle cookies. - If you specify a header `X-Auth-Token` during authentication, the session ID will be returned via this same header. You can then pass that header again for subsequent requests to reuse the session.  If you need to set the session cookie later on, you can call `/api/v1/login/set-cookie` with `X-Auth-Token`. The response will contain the `Set-Cookie` header.  ## Remember Me  During authentication, if a request parameter `remember-me` is passed and set to `true`, the server will also return a `komga-remember-me` cookie. This cookie will be used to login automatically even if the session has expired.  ## Logout  You can explicitly logout an existing session by calling `/api/logout`. This would return a `204`.  ## Deprecation  API endpoints marked as deprecated will be removed in the next major version.
 *
 * The version of the OpenAPI document: 1.24.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Komga.Client.Client.FileParameter;
using OpenAPIDateConverter = Komga.Client.Client.OpenAPIDateConverter;

namespace Komga.Client.Model
{
    /// <summary>
    /// LibraryCreationDto
    /// </summary>
    [DataContract(Name = "LibraryCreationDto")]
    public partial class LibraryCreationDto : IValidatableObject
    {
        /// <summary>
        /// Defines ScanInterval
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ScanIntervalEnum
        {
            /// <summary>
            /// Enum DISABLED for value: DISABLED
            /// </summary>
            [EnumMember(Value = "DISABLED")]
            DISABLED = 1,

            /// <summary>
            /// Enum HOURLY for value: HOURLY
            /// </summary>
            [EnumMember(Value = "HOURLY")]
            HOURLY = 2,

            /// <summary>
            /// Enum EVERY6H for value: EVERY_6H
            /// </summary>
            [EnumMember(Value = "EVERY_6H")]
            EVERY6H = 3,

            /// <summary>
            /// Enum EVERY12H for value: EVERY_12H
            /// </summary>
            [EnumMember(Value = "EVERY_12H")]
            EVERY12H = 4,

            /// <summary>
            /// Enum DAILY for value: DAILY
            /// </summary>
            [EnumMember(Value = "DAILY")]
            DAILY = 5,

            /// <summary>
            /// Enum WEEKLY for value: WEEKLY
            /// </summary>
            [EnumMember(Value = "WEEKLY")]
            WEEKLY = 6
        }


        /// <summary>
        /// Gets or Sets ScanInterval
        /// </summary>
        [DataMember(Name = "scanInterval", IsRequired = true, EmitDefaultValue = true)]
        public ScanIntervalEnum ScanInterval { get; set; }
        /// <summary>
        /// Defines SeriesCover
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SeriesCoverEnum
        {
            /// <summary>
            /// Enum FIRST for value: FIRST
            /// </summary>
            [EnumMember(Value = "FIRST")]
            FIRST = 1,

            /// <summary>
            /// Enum FIRSTUNREADORFIRST for value: FIRST_UNREAD_OR_FIRST
            /// </summary>
            [EnumMember(Value = "FIRST_UNREAD_OR_FIRST")]
            FIRSTUNREADORFIRST = 2,

            /// <summary>
            /// Enum FIRSTUNREADORLAST for value: FIRST_UNREAD_OR_LAST
            /// </summary>
            [EnumMember(Value = "FIRST_UNREAD_OR_LAST")]
            FIRSTUNREADORLAST = 3,

            /// <summary>
            /// Enum LAST for value: LAST
            /// </summary>
            [EnumMember(Value = "LAST")]
            LAST = 4
        }


        /// <summary>
        /// Gets or Sets SeriesCover
        /// </summary>
        [DataMember(Name = "seriesCover", IsRequired = true, EmitDefaultValue = true)]
        public SeriesCoverEnum SeriesCover { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="LibraryCreationDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LibraryCreationDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LibraryCreationDto" /> class.
        /// </summary>
        /// <param name="analyzeDimensions">analyzeDimensions (required).</param>
        /// <param name="convertToCbz">convertToCbz (required).</param>
        /// <param name="emptyTrashAfterScan">emptyTrashAfterScan (required).</param>
        /// <param name="hashFiles">hashFiles (required).</param>
        /// <param name="hashKoreader">hashKoreader (required).</param>
        /// <param name="hashPages">hashPages (required).</param>
        /// <param name="importBarcodeIsbn">importBarcodeIsbn (required).</param>
        /// <param name="importComicInfoBook">importComicInfoBook (required).</param>
        /// <param name="importComicInfoCollection">importComicInfoCollection (required).</param>
        /// <param name="importComicInfoReadList">importComicInfoReadList (required).</param>
        /// <param name="importComicInfoSeries">importComicInfoSeries (required).</param>
        /// <param name="importComicInfoSeriesAppendVolume">importComicInfoSeriesAppendVolume (required).</param>
        /// <param name="importEpubBook">importEpubBook (required).</param>
        /// <param name="importEpubSeries">importEpubSeries (required).</param>
        /// <param name="importLocalArtwork">importLocalArtwork (required).</param>
        /// <param name="importMylarSeries">importMylarSeries (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="oneshotsDirectory">oneshotsDirectory.</param>
        /// <param name="repairExtensions">repairExtensions (required).</param>
        /// <param name="root">root (required).</param>
        /// <param name="scanCbx">scanCbx (required).</param>
        /// <param name="scanDirectoryExclusions">scanDirectoryExclusions (required).</param>
        /// <param name="scanEpub">scanEpub (required).</param>
        /// <param name="scanForceModifiedTime">scanForceModifiedTime (required).</param>
        /// <param name="scanInterval">scanInterval (required).</param>
        /// <param name="scanOnStartup">scanOnStartup (required).</param>
        /// <param name="scanPdf">scanPdf (required).</param>
        /// <param name="seriesCover">seriesCover (required).</param>
        public LibraryCreationDto(bool analyzeDimensions = default, bool convertToCbz = default, bool emptyTrashAfterScan = default, bool hashFiles = default, bool hashKoreader = default, bool hashPages = default, bool importBarcodeIsbn = default, bool importComicInfoBook = default, bool importComicInfoCollection = default, bool importComicInfoReadList = default, bool importComicInfoSeries = default, bool importComicInfoSeriesAppendVolume = default, bool importEpubBook = default, bool importEpubSeries = default, bool importLocalArtwork = default, bool importMylarSeries = default, string name = default, string oneshotsDirectory = default, bool repairExtensions = default, string root = default, bool scanCbx = default, List<string> scanDirectoryExclusions = default, bool scanEpub = default, bool scanForceModifiedTime = default, ScanIntervalEnum scanInterval = default, bool scanOnStartup = default, bool scanPdf = default, SeriesCoverEnum seriesCover = default)
        {
            this.AnalyzeDimensions = analyzeDimensions;
            this.ConvertToCbz = convertToCbz;
            this.EmptyTrashAfterScan = emptyTrashAfterScan;
            this.HashFiles = hashFiles;
            this.HashKoreader = hashKoreader;
            this.HashPages = hashPages;
            this.ImportBarcodeIsbn = importBarcodeIsbn;
            this.ImportComicInfoBook = importComicInfoBook;
            this.ImportComicInfoCollection = importComicInfoCollection;
            this.ImportComicInfoReadList = importComicInfoReadList;
            this.ImportComicInfoSeries = importComicInfoSeries;
            this.ImportComicInfoSeriesAppendVolume = importComicInfoSeriesAppendVolume;
            this.ImportEpubBook = importEpubBook;
            this.ImportEpubSeries = importEpubSeries;
            this.ImportLocalArtwork = importLocalArtwork;
            this.ImportMylarSeries = importMylarSeries;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for LibraryCreationDto and cannot be null");
            }
            this.Name = name;
            this.RepairExtensions = repairExtensions;
            // to ensure "root" is required (not null)
            if (root == null)
            {
                throw new ArgumentNullException("root is a required property for LibraryCreationDto and cannot be null");
            }
            this.Root = root;
            this.ScanCbx = scanCbx;
            // to ensure "scanDirectoryExclusions" is required (not null)
            if (scanDirectoryExclusions == null)
            {
                throw new ArgumentNullException("scanDirectoryExclusions is a required property for LibraryCreationDto and cannot be null");
            }
            this.ScanDirectoryExclusions = scanDirectoryExclusions;
            this.ScanEpub = scanEpub;
            this.ScanForceModifiedTime = scanForceModifiedTime;
            this.ScanInterval = scanInterval;
            this.ScanOnStartup = scanOnStartup;
            this.ScanPdf = scanPdf;
            this.SeriesCover = seriesCover;
            this.OneshotsDirectory = oneshotsDirectory;
        }

        /// <summary>
        /// Gets or Sets AnalyzeDimensions
        /// </summary>
        [DataMember(Name = "analyzeDimensions", IsRequired = true, EmitDefaultValue = true)]
        public bool AnalyzeDimensions { get; set; }

        /// <summary>
        /// Gets or Sets ConvertToCbz
        /// </summary>
        [DataMember(Name = "convertToCbz", IsRequired = true, EmitDefaultValue = true)]
        public bool ConvertToCbz { get; set; }

        /// <summary>
        /// Gets or Sets EmptyTrashAfterScan
        /// </summary>
        [DataMember(Name = "emptyTrashAfterScan", IsRequired = true, EmitDefaultValue = true)]
        public bool EmptyTrashAfterScan { get; set; }

        /// <summary>
        /// Gets or Sets HashFiles
        /// </summary>
        [DataMember(Name = "hashFiles", IsRequired = true, EmitDefaultValue = true)]
        public bool HashFiles { get; set; }

        /// <summary>
        /// Gets or Sets HashKoreader
        /// </summary>
        [DataMember(Name = "hashKoreader", IsRequired = true, EmitDefaultValue = true)]
        public bool HashKoreader { get; set; }

        /// <summary>
        /// Gets or Sets HashPages
        /// </summary>
        [DataMember(Name = "hashPages", IsRequired = true, EmitDefaultValue = true)]
        public bool HashPages { get; set; }

        /// <summary>
        /// Gets or Sets ImportBarcodeIsbn
        /// </summary>
        [DataMember(Name = "importBarcodeIsbn", IsRequired = true, EmitDefaultValue = true)]
        public bool ImportBarcodeIsbn { get; set; }

        /// <summary>
        /// Gets or Sets ImportComicInfoBook
        /// </summary>
        [DataMember(Name = "importComicInfoBook", IsRequired = true, EmitDefaultValue = true)]
        public bool ImportComicInfoBook { get; set; }

        /// <summary>
        /// Gets or Sets ImportComicInfoCollection
        /// </summary>
        [DataMember(Name = "importComicInfoCollection", IsRequired = true, EmitDefaultValue = true)]
        public bool ImportComicInfoCollection { get; set; }

        /// <summary>
        /// Gets or Sets ImportComicInfoReadList
        /// </summary>
        [DataMember(Name = "importComicInfoReadList", IsRequired = true, EmitDefaultValue = true)]
        public bool ImportComicInfoReadList { get; set; }

        /// <summary>
        /// Gets or Sets ImportComicInfoSeries
        /// </summary>
        [DataMember(Name = "importComicInfoSeries", IsRequired = true, EmitDefaultValue = true)]
        public bool ImportComicInfoSeries { get; set; }

        /// <summary>
        /// Gets or Sets ImportComicInfoSeriesAppendVolume
        /// </summary>
        [DataMember(Name = "importComicInfoSeriesAppendVolume", IsRequired = true, EmitDefaultValue = true)]
        public bool ImportComicInfoSeriesAppendVolume { get; set; }

        /// <summary>
        /// Gets or Sets ImportEpubBook
        /// </summary>
        [DataMember(Name = "importEpubBook", IsRequired = true, EmitDefaultValue = true)]
        public bool ImportEpubBook { get; set; }

        /// <summary>
        /// Gets or Sets ImportEpubSeries
        /// </summary>
        [DataMember(Name = "importEpubSeries", IsRequired = true, EmitDefaultValue = true)]
        public bool ImportEpubSeries { get; set; }

        /// <summary>
        /// Gets or Sets ImportLocalArtwork
        /// </summary>
        [DataMember(Name = "importLocalArtwork", IsRequired = true, EmitDefaultValue = true)]
        public bool ImportLocalArtwork { get; set; }

        /// <summary>
        /// Gets or Sets ImportMylarSeries
        /// </summary>
        [DataMember(Name = "importMylarSeries", IsRequired = true, EmitDefaultValue = true)]
        public bool ImportMylarSeries { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets OneshotsDirectory
        /// </summary>
        [DataMember(Name = "oneshotsDirectory", EmitDefaultValue = false)]
        public string OneshotsDirectory { get; set; }

        /// <summary>
        /// Gets or Sets RepairExtensions
        /// </summary>
        [DataMember(Name = "repairExtensions", IsRequired = true, EmitDefaultValue = true)]
        public bool RepairExtensions { get; set; }

        /// <summary>
        /// Gets or Sets Root
        /// </summary>
        [DataMember(Name = "root", IsRequired = true, EmitDefaultValue = true)]
        public string Root { get; set; }

        /// <summary>
        /// Gets or Sets ScanCbx
        /// </summary>
        [DataMember(Name = "scanCbx", IsRequired = true, EmitDefaultValue = true)]
        public bool ScanCbx { get; set; }

        /// <summary>
        /// Gets or Sets ScanDirectoryExclusions
        /// </summary>
        [DataMember(Name = "scanDirectoryExclusions", IsRequired = true, EmitDefaultValue = true)]
        public List<string> ScanDirectoryExclusions { get; set; }

        /// <summary>
        /// Gets or Sets ScanEpub
        /// </summary>
        [DataMember(Name = "scanEpub", IsRequired = true, EmitDefaultValue = true)]
        public bool ScanEpub { get; set; }

        /// <summary>
        /// Gets or Sets ScanForceModifiedTime
        /// </summary>
        [DataMember(Name = "scanForceModifiedTime", IsRequired = true, EmitDefaultValue = true)]
        public bool ScanForceModifiedTime { get; set; }

        /// <summary>
        /// Gets or Sets ScanOnStartup
        /// </summary>
        [DataMember(Name = "scanOnStartup", IsRequired = true, EmitDefaultValue = true)]
        public bool ScanOnStartup { get; set; }

        /// <summary>
        /// Gets or Sets ScanPdf
        /// </summary>
        [DataMember(Name = "scanPdf", IsRequired = true, EmitDefaultValue = true)]
        public bool ScanPdf { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LibraryCreationDto {\n");
            sb.Append("  AnalyzeDimensions: ").Append(AnalyzeDimensions).Append("\n");
            sb.Append("  ConvertToCbz: ").Append(ConvertToCbz).Append("\n");
            sb.Append("  EmptyTrashAfterScan: ").Append(EmptyTrashAfterScan).Append("\n");
            sb.Append("  HashFiles: ").Append(HashFiles).Append("\n");
            sb.Append("  HashKoreader: ").Append(HashKoreader).Append("\n");
            sb.Append("  HashPages: ").Append(HashPages).Append("\n");
            sb.Append("  ImportBarcodeIsbn: ").Append(ImportBarcodeIsbn).Append("\n");
            sb.Append("  ImportComicInfoBook: ").Append(ImportComicInfoBook).Append("\n");
            sb.Append("  ImportComicInfoCollection: ").Append(ImportComicInfoCollection).Append("\n");
            sb.Append("  ImportComicInfoReadList: ").Append(ImportComicInfoReadList).Append("\n");
            sb.Append("  ImportComicInfoSeries: ").Append(ImportComicInfoSeries).Append("\n");
            sb.Append("  ImportComicInfoSeriesAppendVolume: ").Append(ImportComicInfoSeriesAppendVolume).Append("\n");
            sb.Append("  ImportEpubBook: ").Append(ImportEpubBook).Append("\n");
            sb.Append("  ImportEpubSeries: ").Append(ImportEpubSeries).Append("\n");
            sb.Append("  ImportLocalArtwork: ").Append(ImportLocalArtwork).Append("\n");
            sb.Append("  ImportMylarSeries: ").Append(ImportMylarSeries).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  OneshotsDirectory: ").Append(OneshotsDirectory).Append("\n");
            sb.Append("  RepairExtensions: ").Append(RepairExtensions).Append("\n");
            sb.Append("  Root: ").Append(Root).Append("\n");
            sb.Append("  ScanCbx: ").Append(ScanCbx).Append("\n");
            sb.Append("  ScanDirectoryExclusions: ").Append(ScanDirectoryExclusions).Append("\n");
            sb.Append("  ScanEpub: ").Append(ScanEpub).Append("\n");
            sb.Append("  ScanForceModifiedTime: ").Append(ScanForceModifiedTime).Append("\n");
            sb.Append("  ScanInterval: ").Append(ScanInterval).Append("\n");
            sb.Append("  ScanOnStartup: ").Append(ScanOnStartup).Append("\n");
            sb.Append("  ScanPdf: ").Append(ScanPdf).Append("\n");
            sb.Append("  SeriesCover: ").Append(SeriesCover).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Root (string) minLength
            if (this.Root != null && this.Root.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Root, length must be greater than 1.", new [] { "Root" });
            }

            yield break;
        }
    }

}
