/*
 * Komga API
 *
 * Komga REST API.  ## Reference  Check the API reference: - on the [Komga website](https://komga.org/docs/openapi/komga-api) - on any running Komga instance at `/swagger-ui.html` - on [GitHub](https://raw.githubusercontent.com/gotson/komga/refs/heads/master/komga/docs/openapi.json)  ## Authentication  Most endpoints require authentication. Authentication is done using either: - Basic Authentication - Passing an API Key in the `X-API-Key` header  ## Sessions  Upon successful authentication, a session is created, and can be reused.  - By default, a `KOMGA-SESSION` cookie is set via `Set-Cookie` response header. This works well for browsers and clients that can handle cookies. - If you specify a header `X-Auth-Token` during authentication, the session ID will be returned via this same header. You can then pass that header again for subsequent requests to reuse the session.  If you need to set the session cookie later on, you can call `/api/v1/login/set-cookie` with `X-Auth-Token`. The response will contain the `Set-Cookie` header.  ## Remember Me  During authentication, if a request parameter `remember-me` is passed and set to `true`, the server will also return a `komga-remember-me` cookie. This cookie will be used to login automatically even if the session has expired.  ## Logout  You can explicitly logout an existing session by calling `/api/logout`. This would return a `204`.  ## Deprecation  API endpoints marked as deprecated will be removed in the next major version.
 *
 * The version of the OpenAPI document: 1.24.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Komga.Client.Client.FileParameter;
using OpenAPIDateConverter = Komga.Client.Client.OpenAPIDateConverter;

namespace Komga.Client.Model
{
    /// <summary>
    /// PageHashKnownDto
    /// </summary>
    [DataContract(Name = "PageHashKnownDto")]
    public partial class PageHashKnownDto : IValidatableObject
    {
        /// <summary>
        /// Defines Action
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ActionEnum
        {
            /// <summary>
            /// Enum DELETEAUTO for value: DELETE_AUTO
            /// </summary>
            [EnumMember(Value = "DELETE_AUTO")]
            DELETEAUTO = 1,

            /// <summary>
            /// Enum DELETEMANUAL for value: DELETE_MANUAL
            /// </summary>
            [EnumMember(Value = "DELETE_MANUAL")]
            DELETEMANUAL = 2,

            /// <summary>
            /// Enum IGNORE for value: IGNORE
            /// </summary>
            [EnumMember(Value = "IGNORE")]
            IGNORE = 3
        }


        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [DataMember(Name = "action", IsRequired = true, EmitDefaultValue = true)]
        public ActionEnum Action { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PageHashKnownDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PageHashKnownDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PageHashKnownDto" /> class.
        /// </summary>
        /// <param name="action">action (required).</param>
        /// <param name="created">created (required).</param>
        /// <param name="deleteCount">deleteCount (required).</param>
        /// <param name="hash">hash (required).</param>
        /// <param name="lastModified">lastModified (required).</param>
        /// <param name="matchCount">matchCount (required).</param>
        /// <param name="size">size.</param>
        public PageHashKnownDto(ActionEnum action = default, DateTime created = default, int deleteCount = default, string hash = default, DateTime lastModified = default, int matchCount = default, long size = default)
        {
            this.Action = action;
            this.Created = created;
            this.DeleteCount = deleteCount;
            // to ensure "hash" is required (not null)
            if (hash == null)
            {
                throw new ArgumentNullException("hash is a required property for PageHashKnownDto and cannot be null");
            }
            this.Hash = hash;
            this.LastModified = lastModified;
            this.MatchCount = matchCount;
            this.Size = size;
        }

        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [DataMember(Name = "created", IsRequired = true, EmitDefaultValue = true)]
        public DateTime Created { get; set; }

        /// <summary>
        /// Gets or Sets DeleteCount
        /// </summary>
        [DataMember(Name = "deleteCount", IsRequired = true, EmitDefaultValue = true)]
        public int DeleteCount { get; set; }

        /// <summary>
        /// Gets or Sets Hash
        /// </summary>
        [DataMember(Name = "hash", IsRequired = true, EmitDefaultValue = true)]
        public string Hash { get; set; }

        /// <summary>
        /// Gets or Sets LastModified
        /// </summary>
        [DataMember(Name = "lastModified", IsRequired = true, EmitDefaultValue = true)]
        public DateTime LastModified { get; set; }

        /// <summary>
        /// Gets or Sets MatchCount
        /// </summary>
        [DataMember(Name = "matchCount", IsRequired = true, EmitDefaultValue = true)]
        public int MatchCount { get; set; }

        /// <summary>
        /// Gets or Sets Size
        /// </summary>
        [DataMember(Name = "size", EmitDefaultValue = false)]
        public long Size { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PageHashKnownDto {\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  DeleteCount: ").Append(DeleteCount).Append("\n");
            sb.Append("  Hash: ").Append(Hash).Append("\n");
            sb.Append("  LastModified: ").Append(LastModified).Append("\n");
            sb.Append("  MatchCount: ").Append(MatchCount).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
