/*
 * Komga API
 *
 * Komga REST API.  ## Reference  Check the API reference: - on the [Komga website](https://komga.org/docs/openapi/komga-api) - on any running Komga instance at `/swagger-ui.html` - on [GitHub](https://raw.githubusercontent.com/gotson/komga/refs/heads/master/komga/docs/openapi.json)  ## Authentication  Most endpoints require authentication. Authentication is done using either: - Basic Authentication - Passing an API Key in the `X-API-Key` header  ## Sessions  Upon successful authentication, a session is created, and can be reused.  - By default, a `KOMGA-SESSION` cookie is set via `Set-Cookie` response header. This works well for browsers and clients that can handle cookies. - If you specify a header `X-Auth-Token` during authentication, the session ID will be returned via this same header. You can then pass that header again for subsequent requests to reuse the session.  If you need to set the session cookie later on, you can call `/api/v1/login/set-cookie` with `X-Auth-Token`. The response will contain the `Set-Cookie` header.  ## Remember Me  During authentication, if a request parameter `remember-me` is passed and set to `true`, the server will also return a `komga-remember-me` cookie. This cookie will be used to login automatically even if the session has expired.  ## Logout  You can explicitly logout an existing session by calling `/api/logout`. This would return a `204`.  ## Deprecation  API endpoints marked as deprecated will be removed in the next major version.
 *
 * The version of the OpenAPI document: 1.24.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Komga.Client.Client.FileParameter;
using OpenAPIDateConverter = Komga.Client.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Komga.Client.Model
{
    /// <summary>
    /// ReleaseDateAllOfReleaseDate
    /// </summary>
    [JsonConverter(typeof(ReleaseDateAllOfReleaseDateJsonConverter))]
    [DataContract(Name = "ReleaseDate_allOf_releaseDate")]
    public partial class ReleaseDateAllOfReleaseDate : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReleaseDateAllOfReleaseDate" /> class
        /// with the <see cref="After" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of After.</param>
        public ReleaseDateAllOfReleaseDate(After actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReleaseDateAllOfReleaseDate" /> class
        /// with the <see cref="Before" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of Before.</param>
        public ReleaseDateAllOfReleaseDate(Before actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReleaseDateAllOfReleaseDate" /> class
        /// with the <see cref="IsInTheLast" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of IsInTheLast.</param>
        public ReleaseDateAllOfReleaseDate(IsInTheLast actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReleaseDateAllOfReleaseDate" /> class
        /// with the <see cref="IsNotInTheLast" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of IsNotInTheLast.</param>
        public ReleaseDateAllOfReleaseDate(IsNotInTheLast actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReleaseDateAllOfReleaseDate" /> class
        /// with the <see cref="IsNotNull" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of IsNotNull.</param>
        public ReleaseDateAllOfReleaseDate(IsNotNull actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReleaseDateAllOfReleaseDate" /> class
        /// with the <see cref="IsNull" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of IsNull.</param>
        public ReleaseDateAllOfReleaseDate(IsNull actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(After) || value is After)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(Before) || value is Before)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(IsInTheLast) || value is IsInTheLast)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(IsNotInTheLast) || value is IsNotInTheLast)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(IsNotNull) || value is IsNotNull)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(IsNull) || value is IsNull)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: After, Before, IsInTheLast, IsNotInTheLast, IsNotNull, IsNull");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `After`. If the actual instance is not `After`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of After</returns>
        public After GetAfter()
        {
            return (After)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `Before`. If the actual instance is not `Before`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of Before</returns>
        public Before GetBefore()
        {
            return (Before)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `IsInTheLast`. If the actual instance is not `IsInTheLast`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of IsInTheLast</returns>
        public IsInTheLast GetIsInTheLast()
        {
            return (IsInTheLast)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `IsNotInTheLast`. If the actual instance is not `IsNotInTheLast`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of IsNotInTheLast</returns>
        public IsNotInTheLast GetIsNotInTheLast()
        {
            return (IsNotInTheLast)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `IsNotNull`. If the actual instance is not `IsNotNull`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of IsNotNull</returns>
        public IsNotNull GetIsNotNull()
        {
            return (IsNotNull)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `IsNull`. If the actual instance is not `IsNull`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of IsNull</returns>
        public IsNull GetIsNull()
        {
            return (IsNull)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReleaseDateAllOfReleaseDate {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, ReleaseDateAllOfReleaseDate.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of ReleaseDateAllOfReleaseDate
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of ReleaseDateAllOfReleaseDate</returns>
        public static ReleaseDateAllOfReleaseDate FromJson(string jsonString)
        {
            ReleaseDateAllOfReleaseDate newReleaseDateAllOfReleaseDate = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newReleaseDateAllOfReleaseDate;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(After).GetProperty("AdditionalProperties") == null)
                {
                    newReleaseDateAllOfReleaseDate = new ReleaseDateAllOfReleaseDate(JsonConvert.DeserializeObject<After>(jsonString, ReleaseDateAllOfReleaseDate.SerializerSettings));
                }
                else
                {
                    newReleaseDateAllOfReleaseDate = new ReleaseDateAllOfReleaseDate(JsonConvert.DeserializeObject<After>(jsonString, ReleaseDateAllOfReleaseDate.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("After");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into After: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(Before).GetProperty("AdditionalProperties") == null)
                {
                    newReleaseDateAllOfReleaseDate = new ReleaseDateAllOfReleaseDate(JsonConvert.DeserializeObject<Before>(jsonString, ReleaseDateAllOfReleaseDate.SerializerSettings));
                }
                else
                {
                    newReleaseDateAllOfReleaseDate = new ReleaseDateAllOfReleaseDate(JsonConvert.DeserializeObject<Before>(jsonString, ReleaseDateAllOfReleaseDate.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("Before");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into Before: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(IsInTheLast).GetProperty("AdditionalProperties") == null)
                {
                    newReleaseDateAllOfReleaseDate = new ReleaseDateAllOfReleaseDate(JsonConvert.DeserializeObject<IsInTheLast>(jsonString, ReleaseDateAllOfReleaseDate.SerializerSettings));
                }
                else
                {
                    newReleaseDateAllOfReleaseDate = new ReleaseDateAllOfReleaseDate(JsonConvert.DeserializeObject<IsInTheLast>(jsonString, ReleaseDateAllOfReleaseDate.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("IsInTheLast");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into IsInTheLast: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(IsNotInTheLast).GetProperty("AdditionalProperties") == null)
                {
                    newReleaseDateAllOfReleaseDate = new ReleaseDateAllOfReleaseDate(JsonConvert.DeserializeObject<IsNotInTheLast>(jsonString, ReleaseDateAllOfReleaseDate.SerializerSettings));
                }
                else
                {
                    newReleaseDateAllOfReleaseDate = new ReleaseDateAllOfReleaseDate(JsonConvert.DeserializeObject<IsNotInTheLast>(jsonString, ReleaseDateAllOfReleaseDate.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("IsNotInTheLast");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into IsNotInTheLast: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(IsNotNull).GetProperty("AdditionalProperties") == null)
                {
                    newReleaseDateAllOfReleaseDate = new ReleaseDateAllOfReleaseDate(JsonConvert.DeserializeObject<IsNotNull>(jsonString, ReleaseDateAllOfReleaseDate.SerializerSettings));
                }
                else
                {
                    newReleaseDateAllOfReleaseDate = new ReleaseDateAllOfReleaseDate(JsonConvert.DeserializeObject<IsNotNull>(jsonString, ReleaseDateAllOfReleaseDate.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("IsNotNull");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into IsNotNull: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(IsNull).GetProperty("AdditionalProperties") == null)
                {
                    newReleaseDateAllOfReleaseDate = new ReleaseDateAllOfReleaseDate(JsonConvert.DeserializeObject<IsNull>(jsonString, ReleaseDateAllOfReleaseDate.SerializerSettings));
                }
                else
                {
                    newReleaseDateAllOfReleaseDate = new ReleaseDateAllOfReleaseDate(JsonConvert.DeserializeObject<IsNull>(jsonString, ReleaseDateAllOfReleaseDate.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("IsNull");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into IsNull: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newReleaseDateAllOfReleaseDate;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for ReleaseDateAllOfReleaseDate
    /// </summary>
    public class ReleaseDateAllOfReleaseDateJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(ReleaseDateAllOfReleaseDate).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return ReleaseDateAllOfReleaseDate.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return ReleaseDateAllOfReleaseDate.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
