/*
 * Komga API
 *
 * Komga REST API.  ## Reference  Check the API reference: - on the [Komga website](https://komga.org/docs/openapi/komga-api) - on any running Komga instance at `/swagger-ui.html` - on [GitHub](https://raw.githubusercontent.com/gotson/komga/refs/heads/master/komga/docs/openapi.json)  ## Authentication  Most endpoints require authentication. Authentication is done using either: - Basic Authentication - Passing an API Key in the `X-API-Key` header  ## Sessions  Upon successful authentication, a session is created, and can be reused.  - By default, a `KOMGA-SESSION` cookie is set via `Set-Cookie` response header. This works well for browsers and clients that can handle cookies. - If you specify a header `X-Auth-Token` during authentication, the session ID will be returned via this same header. You can then pass that header again for subsequent requests to reuse the session.  If you need to set the session cookie later on, you can call `/api/v1/login/set-cookie` with `X-Auth-Token`. The response will contain the `Set-Cookie` header.  ## Remember Me  During authentication, if a request parameter `remember-me` is passed and set to `true`, the server will also return a `komga-remember-me` cookie. This cookie will be used to login automatically even if the session has expired.  ## Logout  You can explicitly logout an existing session by calling `/api/logout`. This would return a `204`.  ## Deprecation  API endpoints marked as deprecated will be removed in the next major version.
 *
 * The version of the OpenAPI document: 1.24.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Komga.Client.Client.FileParameter;
using OpenAPIDateConverter = Komga.Client.Client.OpenAPIDateConverter;

namespace Komga.Client.Model
{
    /// <summary>
    /// SharedLibrariesUpdateDto
    /// </summary>
    [DataContract(Name = "SharedLibrariesUpdateDto")]
    public partial class SharedLibrariesUpdateDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SharedLibrariesUpdateDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SharedLibrariesUpdateDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SharedLibrariesUpdateDto" /> class.
        /// </summary>
        /// <param name="all">all (required).</param>
        /// <param name="libraryIds">libraryIds (required).</param>
        public SharedLibrariesUpdateDto(bool all = default, List<string> libraryIds = default)
        {
            this.All = all;
            // to ensure "libraryIds" is required (not null)
            if (libraryIds == null)
            {
                throw new ArgumentNullException("libraryIds is a required property for SharedLibrariesUpdateDto and cannot be null");
            }
            this.LibraryIds = libraryIds;
        }

        /// <summary>
        /// Gets or Sets All
        /// </summary>
        [DataMember(Name = "all", IsRequired = true, EmitDefaultValue = true)]
        public bool All { get; set; }

        /// <summary>
        /// Gets or Sets LibraryIds
        /// </summary>
        [DataMember(Name = "libraryIds", IsRequired = true, EmitDefaultValue = true)]
        public List<string> LibraryIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SharedLibrariesUpdateDto {\n");
            sb.Append("  All: ").Append(All).Append("\n");
            sb.Append("  LibraryIds: ").Append(LibraryIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
