name: Build and publish Manga-Service Image
on:

  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [ published, push ]

  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      - external-connectors
    paths:
      - "Common/**"
      - "Common.Database/**"
      - "Extensions/**"
      - "NSwagClients"
      - "Services.Manga/**"
      - "Services.Manga.Tests/**"
      - ".github/workflows/publish-services_manga-image.yml"

jobs:
  docker_publish:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}-services_manga  # it will be lowercased internally
          dockerfile: ./Services.Manga/Dockerfile
          platforms: linux/amd64
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image_tag: external-connectors
          # optionally push to the Docker Hub (docker.io)
          # docker_io_token: ${{ secrets.DOCKER_IO_ACCESS_TOKEN }}  # see https://hub.docker.com/settings/security
          # customize the username to be used when pushing to the Docker Hub
          # docker_io_user: foobar  # see https://github.com/macbre/push-to-ghcr/issues/14