name: Manga Service Unit Tests

on:
  push:
    branches:
      - external-connectors
    paths:
      - "Common/**"
      - "Common.Database/**"
      - "Common.Services/**"
      - "Extensions/**"
      - "NSwagClients"
      - "Services.Manga/**"
      - "Services.Manga.Tests/**"
      - ".github/workflows/unit_tests-services_manga.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'
      - name: Restore dependencies
        run: dotnet restore ./Services.Manga.Tests/Services.Manga.Tests.csproj
      - name: Build the solution
        run: dotnet build ./Services.Manga.Tests/Services.Manga.Tests.csproj --configuration Release --no-restore
      - name: Run unit tests with report
        run: dotnet test ./Services.Manga.Tests/Services.Manga.Tests.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"
      - name: Upload test results
        uses: actions/upload-artifact@v7
        with:
          name: TestResults
          path: ./Tests/TestResults/TestResults.trx